In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:

data = pd.read_sas("drive/MyDrive/Datasets/Health_care.XPT")

In [4]:
df = data.copy()
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,NUMADULT,RESPSLC1,LANDSEX2,LNDSXBRT,SAFETIME,CTELNUM1,CELLFON5,CADULT1,CELLSEX2,CELSXBRT,PVTRESD3,CCLGHOUS,CSTATE1,LANDLINE,HHADULT,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,PRIMINS1,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,EXRACT12,EXEROFT1,EXERHMM1,EXRACT22,EXEROFT2,EXERHMM2,STRENGTH,BPHIGH6,BPMEDS1,CHOLCHK3,TOLDHI3,CHOLMED3,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNC1,CHCOCNC1,CHCCOPD3,ADDEPEV3,CHCKDNY2,HAVARTH4,DIABETE4,DIABAGE4,MARITAL,EDUCA,RENTHOM1,NUMHHOL4,NUMPHON4,CPDEMO1C,VETERAN3,EMPLOY1,CHILDREN,INCOME3,PREGNANT,WEIGHT2,HEIGHT3,DEAF,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,FALL12MN,FALLINJ5,SMOKE100,SMOKDAY2,USENOW3,ECIGNOW2,ALCDAY4,AVEDRNK3,DRNK3GE5,MAXDRNKS,FLUSHOT7,FLSHTMY3,PNEUVAC4,SHINGLE2,HIVTST7,HIVTSTD3,SEATBELT,DRNKDRI2,COVIDPO1,COVIDSM1,COVIDACT,PDIABTS1,PREDIAB2,DIABTYPE,INSULIN1,CHKHEMO3,EYEEXAM1,DIABEYE1,DIABEDU1,FEETSORE,ARTHEXER,ARTHEDU,LMTJOIN3,ARTHDIS2,JOINPAI2,LCSFIRST,LCSLAST,LCSNUMCG,LCSCTSC1,LCSSCNCR,LCSCTWHN,HADMAM,HOWLONG,CERVSCRN,CRVCLCNC,CRVCLPAP,CRVCLHPV,HADHYST2,PSATEST1,PSATIME1,PCPSARS2,PSASUGS1,PCSTALK2,HADSIGM4,COLNSIGM,COLNTES1,SIGMTES1,LASTSIG4,COLNCNCR,VIRCOLO1,VCLNTES2,SMALSTOL,STOLTEST,STOOLDN2,BLDSTFIT,SDNATES1,CNCRDIFF,CNCRAGE,CNCRTYP2,CSRVTRT3,CSRVDOC1,CSRVSUM,CSRVRTRN,CSRVINST,CSRVINSR,CSRVDEIN,CSRVCLIN,CSRVPAIN,CSRVCTL2,INDORTAN,NUMBURN3,SUNPRTCT,WKDAYOUT,WKENDOUT,CIMEMLO1,CDWORRY,CDDISCU1,CDHOUS1,CDSOCIA1,CAREGIV1,CRGVREL4,CRGVLNG1,CRGVHRS1,CRGVPRB3,CRGVALZD,CRGVPER1,CRGVHOU1,CRGVEXPT,LASTSMK2,STOPSMK2,MENTCIGS,MENTECIG,HEATTBCO,FIREARM5,GUNLOAD,LOADULK2,HASYMP1,HASYMP2,HASYMP3,HASYMP4,HASYMP5,HASYMP6,STRSYMP1,STRSYMP2,STRSYMP3,STRSYMP4,STRSYMP5,STRSYMP6,FIRSTAID,ASPIRIN,BIRTHSEX,SOMALE,SOFEMALE,TRNSGNDR,MARIJAN1,MARJSMOK,MARJEAT,MARJVAPE,MARJDAB,MARJOTHR,USEMRJN4,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT1,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,ACEADSAF,ACEADNED,IMFVPLA4,HPVADVC4,HPVADSHT,TETANUS1,COVIDVA1,COVACGE1,COVIDNU2,LSATISFY,EMTSUPRT,SDLONELY,SDHEMPLY,FOODSTMP,SDHFOOD1,SDHBILLS,SDHUTILS,SDHTRNSP,SDHSTRE1,RRCLASS3,RRCOGNT2,RRTREAT,RRATWRK2,RRHCARE4,RRPHYSM2,RCSGEND1,RCSXBRTH,RCSRLTN2,CASTHDX2,CASTHNO2,QSTVER,QSTLANG,_METSTAT,_URBSTAT,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_IMPRACE,_CHISPNC,_CRACE1,CAGEG,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT2,_LLCPWT,_RFHLTH,_PHYS14D,_MENT14D,_HLTHPL1,_HCVU653,_TOTINDA,METVL12_,METVL22_,MAXVO21_,FC601_,ACTIN13_,ACTIN23_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC12,_MINAC22,STRFREQ_,PAMISS3_,PAMIN13_,PAMIN23_,PA3MIN_,PAVIG13_,PAVIG23_,PA3VIGM_,_PACAT3,_PAINDX3,_PA150R4,_PA300R4,_PA30023,_PASTRNG,_PAREC3,_PASTAE3,_RFHYPE6,_CHOLCH3,_RFCHOL3,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR2,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACEPRV,_SEX,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG1,_SMOKER3,_RFSMOK3,_CURECI2,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,b'03012023',b'03',b'01',b'2023',1100.0,b'2023000001',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,3.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,57.0,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,172.0,503.0,2.0,2.0,2.0,1.0,2.0,2.0,88.0,NaN,2.0,NaN,3.0,1.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,5.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11011.0,42.791581,2.0,85.583161,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,941.163973,605.427887,1.0,1.0,1.0,1.0,9.0,2.0,NaN,NaN,1840.0,315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,63.0,160.0,7802.0,3047.0,4.0,2.0,1.0,3.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
1,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000002',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,88.0,88.0,NaN,3.0,1.0,2.0,2.0,1.0,1.0,106.0,30.0,88.0,NaN,NaN,888.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,3.0,NaN,2.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,132.0,409.0,1.0,2.0,2.0,2.0,2.0,2.0,88.0,NaN,2.0,NaN,3.0,1.0,888.0,NaN,NaN,NaN,1.0,92023.0,1.0,2.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,1.0,11012.0,170.429390,1.0,170.429390,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,1874.223855,1121.992705,1.0,1.0,1.0,1.0,9.0,1.0,35.0,NaN,1803.0,309.0,2.0,NaN,30.0,NaN,6000.0,NaN,180.0,5.397605e-79,5.397605e-79,1.000000e+00,360.0,NaN,360.0,180.0,NaN,180.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,13.0,2.0,80.0,6.0,57.0,145.0,5987.0,2856.0,3.0,2.0,1.0,3.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,b'03082023',b'03',b'08',b'2023',1100.0,b'2023000003',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,6.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,205.0,15.0,88.0,NaN,NaN,205.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,3.0,4.0,2.0,2.0,NaN,8.0,2.0,7.0,88.0,2.0,NaN,130.0,504.0,7.0,1.0,1.0,1.0,2.0,2.0,88.0,NaN,1.0,3.0,3.0,1.0,888.0,NaN,NaN,NaN,1.0,112022.0,1.0,1.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,3.0,2.0,2.0,5.0,1.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,3.0,11011.0,42.791581,1.0,42.791581,2.0,9.0,NaN,NaN,NaN,9.0,NaN,1151.603218,600.963308,2.0,2.0,2.0,1.0,9.0,1.0,35.0,NaN,1322.0,227.0,2.0,NaN,15.0,NaN,1167.0,NaN,18.0,5.397605e-79,1.167000e+03,1.000000e+00,36.0,NaN,36.0,18.0,NaN,18.0,9.0,9.0,9.0,9.0,9.0,2.0,9.0,9.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,13.0,2.0,80.0,6.0,64.0,163.0,5897.0,2231.0,2.0,1.0,1.0,2.0,1.0,3.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,b'03062023',b'03',b'06',b'2023',1100.0,b'2023000004',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,88.0,88.0,3.0,1.0,2.0,3.0,1.0,1.0,103.0,30.0,88.0,NaN,NaN,888.0,3.0,NaN,3.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,2.0,1.0,2.0,1.0,3.0,NaN,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,NaN,170.0,506.0,2.0,2.0,2.0,1.0,2.0,2.0,88.0,NaN,2.0,NaN,3.0,1.0,888.0,NaN,NaN,NaN,1.0,102022.0,1.0,2.0,1.0,777777.0,1.0,NaN,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3.0,2.0,2.0,5.0,2.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,2.0,1.0,2.0,11011.0,42.791581,2.0,85.583161,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,941.163973,605.427887,1.0,2.0,1.0,1.0,9.0,1.0,35.0,NaN,1914.0,328.0,2.0,NaN,30.0,NaN,3000.0,NaN,90.0,5.397605e-79,5.397605e-79,1.000000e+00,180.0,NaN,180.0,90.0,NaN,90.0,9.0,1.0,1.0,9.0,9.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,78.0,6.0,66.0,168.0,7711.0,2744.0,3.0,2.0,1.0,3.0,9.0,4.0,1.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000005',2.023000e+09,1.0,1.0,NaN,1.0,2.0,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,88.0,88.0,NaN,3.0,1.0,2.0,1.0,1.0,1.0,102.0,45.0,8.0,107.0,100.0,888.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,1.0,1.0,68.0,3.0,5.0,1.0,2.0,NaN,3.0,2.0,8.0,88.0,7.0,NaN,170.0,508.0,2.0,2.0,1.0,1.0,2.0,1.0,3.0,88.0,2.0,NaN,2.0,1.0,202.0,1.0,88.0,1.0,2.0,NaN,1.0,2.0,2.0,NaN,1.0,88.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,1.0,1.0,5.0,11011.0,42.791581,1.0,42.791581,1.0,9.0,NaN,NaN,NaN,1.0,0.502639,470.581986,281.711042,2.0,1.0,1.0,1.0,9.0,1.0,35.0,33.0,1988.0,341.0,2.0,1.0,45.0,60.0,2000.0,7000.0,90.0,4.200000e+02,5.397605e-79,5.397605e-79,180.0,420.0,600.0,90.0,5.397605e-79,90.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,12.0,2.0,76.0,6.0,68.0,173.0,7711.0,2585.0,3.0,2.0,1.0,3.0,5.0,4.0,1.0,1.0,1.0,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,2.0,1.0,1.0,2.0

In [5]:
df.info(max_cols=600)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 350 columns):
 #    Column    Non-Null Count   Dtype
---   ------    --------------   -----
 0    _STATE    433323 non-null  float64
 1    FMONTH    433323 non-null  float64
 2    IDATE     433323 non-null  object
 3    IMONTH    433323 non-null  object
 4    IDAY      433323 non-null  object
 5    IYEAR     433323 non-null  object
 6    DISPCODE  433323 non-null  float64
 7    SEQNO     433323 non-null  object
 8    _PSU      433323 non-null  float64
 9    CTELENM1  88345 non-null   float64
 10   PVTRESD1  88345 non-null   float64
 11   COLGHOUS  12 non-null      float64
 12   STATERE1  88345 non-null   float64
 13   CELPHON1  88346 non-null   float64
 14   LADULT1   88345 non-null   float64
 15   NUMADULT  88330 non-null   float64
 16   RESPSLC1  52386 non-null   float64
 17   LANDSEX2  70473 non-null   float64
 18   LNDSXBRT  169 non-null     float64
 19   SAFETIME  344978 non-null  float64
 20   CTELNUM1  344978 non-null  float64
 21   CELLFON5  344978 non-null  float64
 22   CADULT1   344978 non-null  float64
 23   CELLSEX2  344976 non-null  float64
 24   CELSXBRT  2578 non-null    float64
 25   PVTRESD3  344978 non-null  float64
 26   CCLGHOUS  1351 non-null    float64
 27   CSTATE1   344968 non-null  float64
 28   LANDLINE  344977 non-null  float64
 29   HHADULT   344974 non-null  float64
 30   SEXVAR    433323 non-null  float64
 31   GENHLTH   433319 non-null  float64
 32   PHYSHLTH  433320 non-null  float64
 33   MENTHLTH  433320 non-null  float64
 34   POORHLTH  252170 non-null  float64
 35   PRIMINS1  433318 non-null  float64
 36   PERSDOC3  433320 non-null  float64
 37   MEDCOST1  433321 non-null  float64
 38   CHECKUP1  433321 non-null  float64
 39   EXERANY2  433321 non-null  float64
 40   EXRACT12  325227 non-null  float64
 41   EXEROFT1  323041 non-null  float64
 42   EXERHMM1  323039 non-null  float64
 43   EXRACT22  323040 non-null  float64
 44   EXEROFT2  228757 non-null  float64
 45   EXERHMM2  228757 non-null  float64
 46   STRENGTH  433319 non-null  float64
 47   BPHIGH6   433320 non-null  float64
 48   BPMEDS1   176222 non-null  float64
 49   CHOLCHK3  433320 non-null  float64
 50   TOLDHI3   381511 non-null  float64
 51   CHOLMED3  379883 non-null  float64
 52   CVDINFR4  433320 non-null  float64
 53   CVDCRHD4  433320 non-null  float64
 54   CVDSTRK3  433319 non-null  float64
 55   ASTHMA3   433320 non-null  float64
 56   ASTHNOW   64366 non-null   float64
 57   CHCSCNC1  433320 non-null  float64
 58   CHCOCNC1  433320 non-null  float64
 59   CHCCOPD3  433320 non-null  float64
 60   ADDEPEV3  433320 non-null  float64
 61   CHCKDNY2  433320 non-null  float64
 62   HAVARTH4  433319 non-null  float64
 63   DIABETE4  433318 non-null  float64
 64   DIABAGE4  59786 non-null   float64
 65   MARITAL   433316 non-null  float64
 66   EDUCA     433314 non-null  float64
 67   RENTHOM1  433315 non-null  float64
 68   NUMHHOL4  88345 non-null   float64
 69   NUMPHON4  7336 non-null    float64
 70   CPDEMO1C  433278 non-null  float64
 71   VETERAN3  432104 non-null  float64
 72   EMPLOY1   430355 non-null  float64
 73   CHILDREN  428231 non-null  float64
 74   INCOME3   425248 non-null  float64
 75   PREGNANT  76208 non-null   float64
 76   WEIGHT2   422712 non-null  float64
 77   HEIGHT3   421674 non-null  float64
 78   DEAF      420248 non-null  float64
 79   BLIND     419243 non-null  float64
 80   DECIDE    418184 non-null  float64
 81   DIFFWALK  417177 non-null  float64
 82   DIFFDRES  416454 non-null  float64
 83   DIFFALON  415463 non-null  float64
 84   FALL12MN  292496 non-null  float64
 85   FALLINJ5  77739 non-null   float64
 86   SMOKE100  413649 non-null  float64
 87   SMOKDAY2  158639 non-null  float64
 88   USENOW3   412886 non-null  float64
 89   ECIGNOW2  411856 non-null  float64
 90   ALCDAY4   407879 non-null  float64
 91   AVEDRNK3  212126 non-null  float64
 92   DRNK3GE5  211689 non-null  float64
 93   MAXDRNKS  211286 non-null  float64
 94   FLUSHOT7  405572 non-null  float64
 95   FLSHTMY3  196982 non-null  float64
 96   PNEUVAC4  404573 non-null  float64
 97   SHINGLE2  256598 non-null  float64
 98   HIVTST7   403710 non-null  float64
 99   HIVTSTD3  133265 non-null  float64
 100  SEATBELT  402545 non-null  float64
 101  DRNKDRI2  213005 non-null  float64
 102  COVIDPO1  401308 non-null  float64
 103  COVIDSM1  201017 non-null  float64
 104  COVIDACT  27036 non-null   float64
 105  PDIABTS1  166249 non-null  float64
 106  PREDIAB2  166152 non-null  float64
 107  DIABTYPE  24275 non-null   float64
 108  INSULIN1  24268 non-null   float64
 109  CHKHEMO3  24260 non-null   float64
 110  EYEEXAM1  24253 non-null   float64
 111  DIABEYE1  24244 non-null   float64
 112  DIABEDU1  24240 non-null   float64
 113  FEETSORE  24238 non-null   float64
 114  ARTHEXER  23323 non-null   float64
 115  ARTHEDU   23296 non-null   float64
 116  LMTJOIN3  23262 non-null   float64
 117  ARTHDIS2  23213 non-null   float64
 118  JOINPAI2  23152 non-null   float64
 119  LCSFIRST  8541 non-null    float64
 120  LCSLAST   6748 non-null    float64
 121  LCSNUMCG  8199 non-null    float64
 122  LCSCTSC1  24095 non-null   float64
 123  LCSSCNCR  10272 non-null   float64
 124  LCSCTWHN  1960 non-null    float64
 125  HADMAM    1093 non-null    float64
 126  HOWLONG   914 non-null     float64
 127  CERVSCRN  1089 non-null    float64
 128  CRVCLCNC  585 non-null     float64
 129  CRVCLPAP  585 non-null     float64
 130  CRVCLHPV  583 non-null     float64
 131  HADHYST2  1083 non-null    float64
 132  PSATEST1  29527 non-null   float64
 133  PSATIME1  16246 non-null   float64
 134  PCPSARS2  16226 non-null   float64
 135  PSASUGS1  16202 non-null   float64
 136  PCSTALK2  29352 non-null   float64
 137  HADSIGM4  10639 non-null   float64
 138  COLNSIGM  7657 non-null    float64
 139  COLNTES1  7449 non-null    float64
 140  SIGMTES1  1226 non-null    float64
 141  LASTSIG4  146 non-null     float64
 142  COLNCNCR  10612 non-null   float64
 143  VIRCOLO1  2598 non-null    float64
 144  VCLNTES2  340 non-null     float64
 145  SMALSTOL  2595 non-null    float64
 146  STOLTEST  2161 non-null    float64
 147  STOOLDN2  2587 non-null    float64
 148  BLDSTFIT  512 non-null     float64
 149  SDNATES1  511 non-null     float64
 150  CNCRDIFF  17161 non-null   float64
 151  CNCRAGE   16629 non-null   float64
 152  CNCRTYP2  16606 non-null   float64
 153  CSRVTRT3  3671 non-null    float64
 154  CSRVDOC1  1808 non-null    float64
 155  CSRVSUM   1807 non-null    float64
 156  CSRVRTRN  1805 non-null    float64
 157  CSRVINST  1360 non-null    float64
 158  CSRVINSR  1799 non-null    float64
 159  CSRVDEIN  1797 non-null    float64
 160  CSRVCLIN  1795 non-null    float64
 161  CSRVPAIN  2773 non-null    float64
 162  CSRVCTL2  222 non-null     float64
 163  INDORTAN  0 non-null       float64
 164  NUMBURN3  0 non-null       float64
 165  SUNPRTCT  0 non-null       float64
 166  WKDAYOUT  0 non-null       float64
 167  WKENDOUT  0 non-null       float64
 168  CIMEMLO1  135909 non-null  float64
 169  CDWORRY   22483 non-null   float64
 170  CDDISCU1  22470 non-null   float64
 171  CDHOUS1   22443 non-null   float64
 172  CDSOCIA1  22410 non-null   float64
 173  CAREGIV1  50811 non-null   float64
 174  CRGVREL4  11483 non-null   float64
 175  CRGVLNG1  11457 non-null   float64
 176  CRGVHRS1  11424 non-null   float64
 177  CRGVPRB3  11397 non-null   float64
 178  CRGVALZD  10081 non-null   float64
 179  CRGVPER1  11347 non-null   float64
 180  CRGVHOU1  11336 non-null   float64
 181  CRGVEXPT  39153 non-null   float64
 182  LASTSMK2  50984 non-null   float64
 183  STOPSMK2  20729 non-null   float64
 184  MENTCIGS  26214 non-null   float64
 185  MENTECIG  12455 non-null   float64
 186  HEATTBCO  237914 non-null  float64
 187  FIREARM5  81310 non-null   float64
 188  GUNLOAD   30177 non-null   float64
 189  LOADULK2  10155 non-null   float64
 190  HASYMP1   10522 non-null   float64
 191  HASYMP2   10507 non-null   float64
 192  HASYMP3   10501 non-null   float64
 193  HASYMP4   10493 non-null   float64
 194  HASYMP5   10484 non-null   float64
 195  HASYMP6   10475 non-null   float64
 196  STRSYMP1  10438 non-null   float64
 197  STRSYMP2  10424 non-null   float64
 198  STRSYMP3  10416 non-null   float64
 199  STRSYMP4  10403 non-null   float64
 200  STRSYMP5  10391 non-null   float64
 201  STRSYMP6  10375 non-null   float64
 202  FIRSTAID  10359 non-null   float64
 203  ASPIRIN   25845 non-null   float64
 204  BIRTHSEX  105230 non-null  float64
 205  SOMALE    135790 non-null  float64
 206  SOFEMALE  153467 non-null  float64
 207  TRNSGNDR  289143 non-null  float64
 208  MARIJAN1  88613 non-null   float64
 209  MARJSMOK  11440 non-null   float64
 210  MARJEAT   11433 non-null   float64
 211  MARJVAPE  11425 non-null   float64
 212  MARJDAB   11413 non-null   float64
 213  MARJOTHR  11405 non-null   float64
 214  USEMRJN4  4754 non-null    float64
 215  ACEDEPRS  56040 non-null   float64
 216  ACEDRINK  55939 non-null   float64
 217  ACEDRUGS  55891 non-null   float64
 218  ACEPRISN  55845 non-null   float64
 219  ACEDIVRC  55808 non-null   float64
 220  ACEPUNCH  55758 non-null   float64
 221  ACEHURT1  55687 non-null   float64
 222  ACESWEAR  55621 non-null   float64
 223  ACETOUCH  55554 non-null   float64
 224  ACETTHEM  55486 non-null   float64
 225  ACEHVSEX  55417 non-null   float64
 226  ACEADSAF  55303 non-null   float64
 227  ACEADNED  55224 non-null   float64
 228  IMFVPLA4  4063 non-null    float64
 229  HPVADVC4  8902 non-null    float64
 230  HPVADSHT  2292 non-null    float64
 231  TETANUS1  12840 non-null   float64
 232  COVIDVA1  131896 non-null  float64
 233  COVACGE1  20255 non-null   float64
 234  COVIDNU2  110754 non-null  float64
 235  LSATISFY  226676 non-null  float64
 236  EMTSUPRT  226318 non-null  float64
 237  SDLONELY  225998 non-null  float64
 238  SDHEMPLY  225739 non-null  float64
 239  FOODSTMP  225475 non-null  float64
 240  SDHFOOD1  225129 non-null  float64
 241  SDHBILLS  224861 non-null  float64
 242  SDHUTILS  224624 non-null  float64
 243  SDHTRNSP  224266 non-null  float64
 244  SDHSTRE1  223493 non-null  float64
 245  RRCLASS3  142505 non-null  float64
 246  RRCOGNT2  142164 non-null  float64
 247  RRTREAT   141806 non-null  float64
 248  RRATWRK2  70209 non-null   float64
 249  RRHCARE4  141333 non-null  float64
 250  RRPHYSM2  141022 non-null  float64
 251  RCSGEND1  49434 non-null   float64
 252  RCSXBRTH  2634 non-null    float64
 253  RCSRLTN2  49024 non-null   float64
 254  CASTHDX2  47624 non-null   float64
 255  CASTHNO2  4749 non-null    float64
 256  QSTVER    433323 non-null  float64
 257  QSTLANG   433323 non-null  float64
 258  _METSTAT  425000 non-null  float64
 259  _URBSTAT  425000 non-null  float64
 260  MSCODE    85527 non-null   float64
 261  _STSTR    433323 non-null  float64
 262  _STRWT    433323 non-null  float64
 263  _RAWRAKE  433323 non-null  float64
 264  _WT2RAKE  433323 non-null  float64
 265  _IMPRACE  433323 non-null  float64
 266  _CHISPNC  277030 non-null  float64
 267  _CRACE1   51210 non-null   float64
 268  CAGEG     41925 non-null   float64
 269  _CLLCPWT  49541 non-null   float64
 270  _DUALUSE  433323 non-null  float64
 271  _DUALCOR  144162 non-null  float64
 272  _LLCPWT2  433323 non-null  float64
 273  _LLCPWT   433323 non-null  float64
 274  _RFHLTH   433323 non-null  float64
 275  _PHYS14D  433323 non-null  float64
 276  _MENT14D  433323 non-null  float64
 277  _HLTHPL1  433323 non-null  float64
 278  _HCVU653  433323 non-null  float64
 279  _TOTINDA  433323 non-null  float64
 280  METVL12_  323041 non-null  float64
 281  METVL22_  228757 non-null  float64
 282  MAXVO21_  433323 non-null  float64
 283  FC601_    433323 non-null  float64
 284  ACTIN13_  317417 non-null  float64
 285  ACTIN23_  225086 non-null  float64
 286  PADUR1_   315638 non-null  float64
 287  PADUR2_   223535 non-null  float64
 288  PAFREQ1_  316148 non-null  float64
 289  PAFREQ2_  224522 non-null  float64
 290  _MINAC12  310832 non-null  float64
 291  _MINAC22  310052 non-null  float64
 292  STRFREQ_  419150 non-null  float64
 293  PAMISS3_  433323 non-null  float64
 294  PAMIN13_  305711 non-null  float64
 295  PAMIN23_  217736 non-null  float64
 296  PA3MIN_   310074 non-null  float64
 297  PAVIG13_  312636 non-null  float64
 298  PAVIG23_  221455 non-null  float64
 299  PA3VIGM_  314603 non-null  float64
 300  _PACAT3   433323 non-null  float64
 301  _PAINDX3  433323 non-null  float64
 302  _PA150R4  433323 non-null  float64
 303  _PA300R4  433323 non-null  float64
 304  _PA30023  433323 non-null  float64
 305  _PASTRNG  433323 non-null  float64
 306  _PAREC3   433323 non-null  float64
 307  _PASTAE3  433323 non-null  float64
 308  _RFHYPE6  433323 non-null  float64
 309  _CHOLCH3  433323 non-null  float64
 310  _RFCHOL3  381512 non-null  float64
 311  _MICHD    428738 non-null  float64
 312  _LTASTH1  433323 non-null  float64
 313  _CASTHM1  433323 non-null  float64
 314  _ASTHMS1  433323 non-null  float64
 315  _DRDXAR2  430763 non-null  float64
 316  _MRACE1   433069 non-null  float64
 317  _HISPANC  433323 non-null  float64
 318  _RACE     433237 non-null  float64
 319  _RACEG21  433237 non-null  float64
 320  _RACEGR3  433237 non-null  float64
 321  _RACEPRV  433237 non-null  float64
 322  _SEX      433323 non-null  float64
 323  _AGEG5YR  433323 non-null  float64
 324  _AGE65YR  433323 non-null  float64
 325  _AGE80    433323 non-null  float64
 326  _AGE_G    433323 non-null  float64
 327  HTIN4     405324 non-null  float64
 328  HTM4      411182 non-null  float64
 329  WTKG3     399172 non-null  float64
 330  _BMI5     392788 non-null  float64
 331  _BMI5CAT  392788 non-null  float64
 332  _RFBMI5   433323 non-null  float64
 333  _CHLDCNT  433323 non-null  float64
 334  _EDUCAG   433323 non-null  float64
 335  _INCOMG1  433323 non-null  float64
 336  _SMOKER3  433323 non-null  float64
 337  _RFSMOK3  433323 non-null  float64
 338  _CURECI2  433323 non-null  float64
 339  DRNKANY6  433323 non-null  float64
 340  DROCDY4_  433323 non-null  float64
 341  _RFBING6  433323 non-null  float64
 342  _DRNKWK2  433323 non-null  float64
 343  _RFDRHV8  433323 non-null  float64
 344  _FLSHOT7  170823 non-null  float64
 345  _PNEUMO3  170823 non-null  float64
 346  _AIDTST4  403710 non-null  float64
 347  _RFSEAT2  433323 non-null  float64
 348  _RFSEAT3  433323 non-null  float64
 349  _DRNKDRV  433323 non-null  float64
dtypes: float64(345), object(5)
memory usage: 1.1+ GB

In [6]:
df.shape

(433323, 350)

## Check Duplicates and Anomalies

In [7]:
# Checking if there are any duplicate records
df['SEQNO'].nunique()

26444

In [8]:
df['_PSU'].nunique()

26444

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.shape

(433323, 350)

Identifying columns and properties

In [11]:
df['_DRNKDRV'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 433323 entries, 0 to 433322
Series name: _DRNKDRV
Non-Null Count   Dtype
--------------   -----
433323 non-null  float64
dtypes: float64(1)
memory usage: 3.3 MB

In [12]:
df['_DRNKDRV'].value_counts()

_DRNKDRV
9.0    221590
2.0    205541
1.0      6192
Name: count, dtype: int64

In [13]:
# Columns which are trivial or unnecessary
cols1 = ['FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'SEQNO', '_PSU', 'CTELENM1', 'PVTRESD1', 'COLGHOUS', 'CELPHON1', 'LANDSEX2', 'CTELNUM1', 'CELLFON5', 'CELLSEX2',
 'PVTRESD3', 'CCLGHOUS', 'LANDLINE' ]

# columns that have wrong data in them or very small percentage of non-null data
cols2 = ['RESPSLC1', 'NUMPHON4', 'PDIABTS1', 'PREDIAB2', 'DIABEYE1', 'DIABEDU1', 'CRVCLCNC', 'PCPSARS2', 'PCSTALK2', 'SDNATES1', 'CSRVTRT3', 'INDORTAN', 'NUMBURN3', 'SUNPRTCT',
 'WKDAYOUT', 'WKENDOUT', 'ACETOUCH', 'ACETTHEM', 'ACEHVSEX', 'COVACGE1', '_PA150R4', '_PA300R4', '_CHOLCH3' ]

# columns which have 1=yes and 2=No
cols3 = ['STATERE1', 'LADULT1', 'SAFETIME', 'CADULT1', 'CSTATE1', 'MEDCOST1', 'EXERANY2', 'BPMEDS1', 'TOLDHI3', 'CHOLMED3', 'CVDINFR4', 'TOLDHI3', 'CHOLMED3', 'CVDINFR4',
 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNC1', 'CHCOCNC1', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'HAVARTH4', 'VETERAN3', 'PREGNANT', 'DEAF', 'BLIND',
 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'FLUSHOT7', 'PNEUVAC4', 'SHINGLE2', 'HIVTST7', 'COVIDPO1', 'COVIDSM1', 'INSULIN1', 'FEETSORE', 'ARTHEXER',
 'ARTHEDU', 'LMTJOIN3', 'LCSCTSC1', 'LCSSCNCR', 'HADMAM', 'CERVSCRN', 'CRVCLPAP', 'CRVCLHPV', 'HADHYST2', 'PSATEST1', 'HADSIGM4', 'COLNCNCR', 'VIRCOLO1', 'SMALSTOL',
 'BLDSTFIT', 'CSRVSUM', 'CSRVRTRN', 'CSRVINST', 'CSRVINSR', 'CSRVDEIN', 'CSRVCLIN', 'CSRVPAIN', 'CIMEMLO1', 'CDDISCU1', 'CAREGIV1', 'CRGVALZD', 'CRGVPER1', 'CRGVHOU1',
 'STOPSMK2', 'MENTCIGS', 'MENTECIG', 'HEATTBCO', 'FIREARM5', 'GUNLOAD', 'LOADULK2', 'HASYMP1', 'HASYMP2', 'HASYMP3', 'HASYMP4', 'HASYMP5', 'HASYMP6', 'STRSYMP1', 'STRSYMP2',
 'STRSYMP3', 'STRSYMP4', 'STRSYMP5', 'STRSYMP6', 'MARJSMOK', 'MARJEAT', 'MARJVAPE', 'MARJDAB', 'MARJOTHR', 'ACEDEPRS', 'ACEDRINK', 'ACEDRUGS', 'ACEPRISN', 'ACEDIVRC',
  'HPVADVC4', 'COVIDVA1', 'SDHEMPLY', 'FOODSTMP', 'SDHUTILS', 'SDHTRNSP', 'CASTHDX2', 'CASTHNO2', '_CHISPNC', '_DUALUSE', '_HLTHPL1', '_HCVU653', '_PASTAE3', '_LTASTH1',
 '_HISPANC', 'DRNKANY6', '_FLSHOT7', '_PNEUMO3', '_AIDTST4' ]

# columns which have 1=No and 2=Yes
cols4 = ['_RFHYPE6', '_RFCHOL3', '_RFBMI5', '_RFSMOK3', '_RFBING6', '_RFDRHV8', '_DRNKDRV']

# columns which have been encoded
cols5 = ['DISPCODE', 'SEXVAR', 'GENHLTH', 'PERSDOC3', 'CHECKUP1', 'BPHIGH6',
 'CHOLCHK3', 'DIABETE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'CPDEMO1C', 'EMPLOY1', 'INCOME3', 'SMOKDAY2', 'USENOW3', 'ECIGNOW2', 'ALCDAY4', 'SEATBELT', 'COVIDACT',
 'DIABTYPE', 'EYEEXAM1', 'CRGVLNG1', 'CRGVHRS1', 'SOMALE', 'SOFEMALE', 'USEMRJN4', 'ACEPUNCH', 'ACEHURT1', 'ACESWEAR', 'TETANUS1', 'LSATISFY', 'EMTSUPRT', 'SDLONELY',
 'SDHFOOD1', 'SDHSTRE1', 'QSTLANG', '_METSTAT', '_URBSTAT', 'MSCODE', '_IMPRACE', '_CRACE1', '_RFHLTH', '_PHYS14D', '_MENT14D', '_TOTINDA', 'ACTIN13_', 'ACTIN23_',
 '_PACAT3', '_PAINDX3', '_PA30023', '_PASTRNG', '_PAREC3', '_MICHD', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV', '_SEX', '_AGEG5YR',
 '_AGE65YR', '_AGE_G', '_BMI5CAT', '_CHLDCNT', '_EDUCAG', '_INCOMG1', '_SMOKER3', '_CURECI2', '_RFSEAT2', '_RFSEAT3' ]

# numeric columns
cols6 = ['NUMADULT', 'HHADULT', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS1', 'DIABAGE4', 'NUMHHOL4', 'CHILDREN', 'WEIGHT2', 'HEIGHT3', 'FALL12MN', 'FALLINJ5', 'AVEDRNK3', 'DRNK3GE5', 'MAXDRNKS',
 'DRNKDRI2', 'CHKHEMO3', 'JOINPAI2', 'LCSFIRST', 'LCSLAST', 'LCSNUMCG',  'LCSCTWHN', 'HOWLONG', 'COLNTES1', 'CNCRAGE', 'CSRVDOC1', 'CSRVCTL2', 'MARIJAN1', 'ACEADSAF',
 'ACEADNED', 'HPVADSHT', 'COVIDNU2', 'RRCOGNT2', '_STSTR', '_STRWT', '_LLCPWT2', 'METVL12_', 'METVL22_', 'MAXVO21_', 'FC601_', 'PADUR1_', 'PADUR2_', 'PAFREQ1_',
 'PAFREQ2_', '_MINAC12', '_MINAC22', 'STRFREQ_', 'PAMIN13_', 'PAMIN23_', 'PA3MIN_', 'PAVIG13_', 'PAVIG23_', 'PA3VIGM_', '_AGE80', 'HTIN4', 'HTM4', 'WTKG3', 'DROCDY4_',
 '_DRNKWK2' ]

# columns with no error
cols7 = ['FLSHTMY3', 'HIVTSTD3', 'ARTHDIS2', 'PSATIME1', 'PSASUGS1', 'COLNSIGM', 'SIGMTES1', 'LASTSIG4', 'VCLNTES2', 'STOLTEST', 'STOOLDN2', 'CNCRDIFF', 'CNCRTYP2', 'CDWORRY',
 'CDHOUS1', 'CDSOCIA1', 'CRGVREL4', 'CRGVPRB3', 'CRGVEXPT', 'LASTSMK2', 'FIRSTAID', 'ASPIRIN', 'IMFVPLA4', 'SDHBILLS', 'RRCLASS3', 'RRTREAT', 'RRATWRK2', 'RRHCARE4',
 'RRPHYSM2', 'RCSRLTN2', 'QSTVER', '_RAWRAKE', 'CAGEG', '_DUALCOR', 'PAMISS3_', '_MRACE1', 'EXRACT12', 'EXEROFT1', 'EXERHMM1',  'EXRACT22', 'EXEROFT2', 'STRENGTH']

In [14]:
# dropping columns which are trivial or unnecessary
df.drop(cols1, axis=1, inplace=True)

# dropping columns which have wrong data in them or very small percentage of non-null data
df.drop(cols2, axis=1, inplace=True)

In [15]:
# encoding yes no type columns
for i in cols3:
  df[i] = df[i].replace({1:"Yes", 2:"No", 7:"Don't know / Not sure", 9:"Refused"})

for i in cols4:
  df[i] = df[i].replace({1:"No", 2:"Yes", 7:"Don't know / Not sure", 9:"Refused"})

df[cols3].fillna("Not asked or missing", inplace=True)

df[cols4].fillna("Not asked or missing", inplace=True)

/tmp/ipykernel_10339/2416156722.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols3].fillna("Not asked or missing", inplace=True)
/tmp/ipykernel_10339/2416156722.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols4].fillna("Not asked or missing", inplace=True)

In [16]:
df['_DRNKWK2'].value_counts()

_DRNKWK2
5.397605e-79    191402
9.990000e+04     32825
2.300000e+01     22605
4.700000e+01     19269
9.300000e+01     12429
2.000000e+02     11568
1.000000e+02     10858
4.000000e+02      9835
7.000000e+02      9519
7.000000e+01      8690
1.400000e+03      7809
6.000000e+02      7774
1.400000e+02      7562
3.000000e+02      6480
2.330000e+02      5698
1.870000e+02      5241
4.670000e+02      5115
1.170000e+02      4211
2.800000e+02      4142
8.000000e+02      3375
3.500000e+02      3320
2.100000e+03      3041
5.000000e+02      2836
1.000000e+03      2835
1.200000e+03      2784
9.330000e+02      2709
3.730000e+02      2122
9.000000e+02      2039
2.100000e+02      1757
5.600000e+02      1716
2.800000e+03      1483
1.167000e+03      1321
5.830000e+02      1315
1.500000e+03      1056
3.270000e+02      1039
4.200000e+02       982
4.200000e+03       884
3.500000e+03       814
1.050000e+03       807
1.630000e+02       763
2.000000e+03       619
6.530000e+02       613
1.800000e+03       573
1.600000e+03       572
8.400000e+02       551
1.750000e+03       543
1.120000e+03       447
4.900000e+02       431
1.867000e+03       418
1.307000e+03       410
7.470000e+02       402
2.333000e+03       397
2.400000e+03       392
5.600000e+03       272
3.000000e+03       267
7.000000e+03       234
9.800000e+02       216
8.400000e+03       212
1.960000e+03       205
4.900000e+03       175
2.500000e+03       160
1.680000e+03       144
3.600000e+03       130
8.170000e+02       120
1.260000e+03       113
6.300000e+02       101
1.353000e+03        86
2.613000e+03        82
4.000000e+03        79
4.667000e+03        78
6.070000e+02        75
2.917000e+03        73
1.633000e+03        65
5.130000e+02        64
2.030000e+03        62
1.050000e+04        61
3.267000e+03        60
6.770000e+02        60
1.213000e+03        59
2.240000e+03        58
1.493000e+03        58
1.027000e+03        55
3.200000e+03        51
6.000000e+03        49
6.300000e+03        47
3.733000e+03        47
3.360000e+03        42
3.920000e+03        41
1.890000e+03        40
2.450000e+03        38
4.800000e+03        37
1.470000e+03        36
2.100000e+04        36
5.000000e+03        35
1.143000e+03        33
1.400000e+04        33
2.707000e+03        32
3.970000e+02        32
4.500000e+03        30
2.520000e+03        29
1.820000e+03        26
1.073000e+03        24
7.930000e+02        24
1.540000e+03        24
1.120000e+04        21
1.260000e+04        21
5.833000e+03        20
1.190000e+03        20
1.680000e+04        19
3.030000e+02        18
5.250000e+03        18
4.083000e+03        16
3.150000e+03        16
2.570000e+02        15
9.800000e+03        14
4.060000e+03        14
2.567000e+03        14
9.100000e+02        14
1.587000e+03        14
5.370000e+02        13
2.427000e+03        11
7.500000e+03        11
1.610000e+03        11
2.940000e+03        10
7.700000e+02        10
9.000000e+03        10
5.227000e+03        10
9.333000e+03         9
6.533000e+03         9
1.000000e+04         9
2.700000e+03         9
3.033000e+03         9
2.053000e+03         9
8.750000e+03         8
7.200000e+03         8
1.100000e+03         8
3.383000e+03         7
3.640000e+03         7
3.220000e+03         7
3.780000e+03         7
4.573000e+03         7
1.750000e+04         6
3.500000e+04         6
8.000000e+03         6
1.190000e+04         6
4.480000e+03         6
2.147000e+03         6
2.287000e+03         6
5.400000e+03         6
1.517000e+03         5
2.800000e+04         5
8.870000e+02         5
4.200000e+04         5
3.080000e+03         5
5.367000e+03         5
8.120000e+03         5
2.987000e+03         4
7.700000e+03         4
3.000000e+04         4
7.840000e+03         4
1.500000e+04         4
3.430000e+03         4
1.200000e+04         4
9.600000e+03         4
3.593000e+03         3
5.320000e+04         3
6.767000e+03         3
2.777000e+03         3
4.107000e+03         3
6.400000e+03         3
4.410000e+03         3
2.520000e+04         3
5.413000e+03         3
5.040000e+03         3
1.983000e+03         3
4.430000e+02         2
1.330000e+03         2
1.082700e+04         2
5.200000e+03         2
4.737000e+03         2
2.200000e+03         2
9.660000e+03         2
5.133000e+03         2
1.890000e+04         2
1.600000e+04         2
3.173000e+03         2
1.283000e+03         2
4.247000e+03         2
3.150000e+04         2
7.280000e+03         2
6.800000e+03         2
3.360000e+04         2
1.800000e+04         2
2.600000e+03         2
4.853000e+03         2
3.900000e+03         2
1.300000e+03         2
8.167000e+03         2
9.100000e+03         2
1.166700e+04         2
1.306700e+04         2
1.458300e+04         2
6.440000e+03         2
6.067000e+03         2
7.560000e+03         2
6.720000e+03         2
6.090000e+03         2
1.470000e+04         2
2.660000e+03         1
2.613300e+04         1
9.450000e+03         1
1.421000e+04         1
4.130000e+04         1
4.340000e+04         1
6.500000e+03         1
4.550000e+03         1
1.250000e+04         1
3.300000e+03         1
2.240000e+04         1
1.610000e+04         1
3.850000e+03         1
4.400000e+03         1
7.187000e+03         1
1.073300e+04         1
3.400000e+03         1
2.730000e+03         1
4.900000e+04         1
2.706700e+04         1
2.450000e+04         1
3.600000e+04         1
1.829300e+04         1
3.967000e+03         1
5.250000e+04         1
6.417000e+03         1
3.337000e+03         1
1.440000e+04         1
7.513000e+03         1
1.540000e+04         1
9.473000e+03         1
7.467000e+03         1
1.620000e+04         1
5.110000e+04         1
1.960000e+04         1
4.830000e+04         1
1.330000e+04         1
5.973000e+03         1
3.757000e+03         1
2.333300e+04         1
1.962300e+04         1
2.000000e+04         1
2.683000e+03         1
1.520000e+04         1
1.194700e+04         1
2.380000e+03         1
1.344000e+04         1
5.880000e+03         1
Name: count, dtype: int64

In [17]:
# replacing encoded columns back to categorical columns
df['DISPCODE'] = df['DISPCODE'].replace({1100:"Complete", 1200:"Partial Complete"})
df['SEXVAR'] = df['SEXVAR'].replace({1:"Male", 2:"Female"})
df['GENHLTH'] = df['GENHLTH'].replace({1:"Excellent", 2:"Very Good", 3:"Good", 4:"Fair", 5:"Poor", 7:"Don't Know / Not Sure", 9:"Refused"})
df['PERSDOC3'] = df['PERSDOC3'].replace({1:"Yes, Only one", 2:"Yes, more than one", 3:"No", 7:"Don't Know / Not Sure", 9:"Refused"})
df['CHECKUP1'] = df['CHECKUP1'].replace({1:"Within past year", 2:"Within past 2 years", 3:"Within past 5 years", 4:"5+ years ago", 8:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['BPHIGH6'] = df['BPHIGH6'].replace({1:"Yes", 2:"Yes, during preganancy", 3:"No", 4:"Told boderline", 7:"Don't Know / Not Sure", 9:"Refused"})
df['CHOLCHK3'] = df['CHOLCHK3'].replace({1:"Within past year", 2:"Within past 2 years", 3:"Within past 3 years", 4:"Within past 4 years", 5:"Within past 5 years", 6:"Within past 6 years",  7:"Don't Know / Not Sure", 9:"Refused", 8:"Refused"})
df['DIABETE4'] = df['DIABETE4'].replace({1:"Yes", 2:"Yes during pregnancy", 3:"No", 4:"No, pre-diabetes or boderline", 7:"Don't Know / Not Sure", 9:"Refused"})
df['MARITAL'] = df['MARITAL'].replace({1:"Married", 2:"Divorced", 3:"Widowed", 4:"Separated", 5:"Never Married", 6:"Unmarried Couple", 7:"Don't Know / Not Sure", 9:"Refused"})
df['EDUCA'] = df['EDUCA'].replace({1:"Never attended school", 2:"Grades 1-8", 3:"Grades 9-11", 4:"Grade 12 or GED", 5:"College 1-3 years", 6:"College 4+ years", 7:"Don't Know / Not Sure", 9:"Refused"})
df['RENTHOM1'] = df['RENTHOM1'].replace({1:"Own", 2:"Rent", 3:"Other arrangement", 7:"Don't Know / Not Sure", 9:"Refused"})
df['EMPLOY1'] = df['EMPLOY1'].replace({1:"Employed for wages", 2:"Self-employed", 3:"Out of work 1+ year", 4:"Out of work <1 year", 5:"Homemaker", 6:"Student", 7:"Retired", 8:"unable to work", 9:"Refused"})
df['INCOME3'] = df['INCOME3'].replace({1:"<10K", 2:"10K-15K", 3:"15K-20K", 4:"20K-25K", 5:"25K-35K", 6:"35K-50K", 7:"50K-75K", 8:"75K-100K", 9:"100K-150K", 10:"150K-200K", 11:"200K+", 77:"Don't Know / Not Sure", 99:"Refused"})
df['SMOKDAY2'] = df['SMOKDAY2'].replace({1:"Everyday", 2:"Somedays", 3:"Not at all", 7:"Don't Know / Not Sure", 9:"Refused"})
df['USENOW3'] = df['USENOW3'].replace({1:"Everyday", 2:"Somedays", 3:"Not at all", 7:"Don't Know / Not Sure", 9:"Refused"})
df['ECIGNOW2'] = df['ECIGNOW2'].replace({1:"Everyday", 2:"Somedays", 3:"Not at all", 4:"Never Used", 7:"Don't Know / Not Sure", 9:"Refused"})
df['SEATBELT'] = df['SEATBELT'].replace({1:"Always", 2:"Nearly Always", 3:"Sometimes", 4:"Seldom", 5:"Never", 7:"Don't Know / Not Sure", 9:"Refused", 8:"Never drive/ride"})
df['COVIDACT'] = df['COVIDACT'].replace({1:"Yes, a lot", 2:"Yes, a little", 3:"Not at all", 7:"Don't Know / Not Sure", 9:"Refused"})
df['DIABTYPE'] = df['DIABTYPE'].replace({1:"Type 1", 2:"Type 2", 7:"Don't Know / Not Sure", 9:"Refused"})
df['EYEEXAM1'] = df['EYEEXAM1'].replace({1:"Within past month", 2:"Within past year", 3:"Within past 2 years", 4:"Within past 3 years", 7:"Don't Know / Not Sure", 9:"Refused", 8:"Never"})
df['CRGVLNG1'] = df['CRGVLNG1'].replace({1:"<30 days", 2:"1-6 months", 3:"6 months - 2 years", 4:"2-5 years", 5:"5+ years", 7:"Don't Know / Not Sure", 9:"Refused"})
df['CRGVHRS1'] = df['CRGVHRS1'].replace({1:"Upto 8 hours", 2: "9-19 hours", 3:"20-39 hours", 4:"40+ hours", 7:"Don't Know / Not Sure", 9:"Refused"})
df['SOMALE'] = df['SOMALE'].replace({1:"Gay", 2:"Straight", 3:"Bisexual", 4:"Something else", 7:"Don't Know / Not Sure", 9:"Refused"})
df['SOFEMALE'] = df['SOFEMALE'].replace({1:"Lesbian/Gay", 2:"Straight", 3:"Bisexual", 4:"Something else", 7:"Don't Know / Not Sure", 9:"Refused"})
df['USEMRJN4'] = df['USEMRJN4'].replace({1:"Medical", 2:"Non-medical", 3:"Both", 4:"Neither", 5:"Neither", 7:"Don't Know / Not Sure", 9:"Refused"})
df['ACEPUNCH'] = df['ACEPUNCH'].replace({1:"Never", 2:"Once", 3:"More than once", 7:"Don't Know / Not Sure", 9:"Refused"})
df['ACEHURT1'] = df['ACEHURT1'].replace({1:"Never", 2:"Once", 3:"More than once", 7:"Don't Know / Not Sure", 9:"Refused"})
df['ACESWEAR'] = df['ACESWEAR'].replace({1:"Never", 2:"Once", 3:"More than once", 7:"Don't Know / Not Sure", 9:"Refused"})
df['TETANUS1'] = df['TETANUS1'].replace({1:"Yes, Tdap", 2:"Yes, but not Tdap", 3:"Yes, not sure of type", 4:"No", 7:"Don't Know / Not Sure", 9:"Refused"})
df['LSATISFY'] = df['LSATISFY'].replace({1:"Very Satisfied", 2:"Satisfied", 3:"Dissatisfied", 4:"Very dissatisfied", 7:"Don't Know / Not Sure", 9:"Refused"})
df['EMTSUPRT'] = df['EMTSUPRT'].replace({1:"Always", 2:"Usually", 3:"Sometimes", 4:"Rarely", 5:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['SDLONELY'] = df['SDLONELY'].replace({1:"Always", 2:"Usually", 3:"Sometimes", 4:"Rarely", 5:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['SDHFOOD1'] = df['SDHFOOD1'].replace({1:"Always", 2:"Usually", 3:"Sometimes", 4:"Rarely", 5:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['SDHSTRE1'] = df['SDHSTRE1'].replace({1:"Always", 2:"Usually", 3:"Sometimes", 4:"Rarely", 5:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['QSTLANG'] = df['QSTLANG'].replace({1:"English", 2:"Spanish", 3:"Other"})
df['_METSTAT'] = df['_METSTAT'].replace({1:"Metropolitian area", 2:"Non-metropolitian area"})
df['_URBSTAT'] = df['_URBSTAT'].replace({1:"Urban", 2:"Rural"})
df['MSCODE'] = df['MSCODE'].replace({1:"Centre of MSA", 2:"Outside MSA centre", 3:"Suburban", 5:"Non-MSA"})
df['_IMPRACE'] = df['_IMPRACE'].replace({1:"White NH", 2:"Black NH", 3:"Asian NH", 4:"AI/AN NH", 5:"Hispanic", 6:"Other"})
df['_RFHLTH'] = df['_RFHLTH'].replace({1:"Good or Better", 2:"Fair or Poor", 9:"Don't Know / Not Sure" })
df['_PHYS14D'] = df['_PHYS14D'].replace({1:"0 days", 2:"1-13 days", 3:"14+ days", 9:"Missing"})
df['_MENT14D'] = df['_MENT14D'].replace({1:"0 days", 2:"1-13 days", 3:"14+ days", 9:"Missing"})
df['_TOTINDA'] = df['_TOTINDA'].replace({1:"Had exercise", 2:"No exercise", 9:"Donot know or missing"})
df['ACTIN13_'] = df['ACTIN13_'].replace({1:"Active", 2:"Insufficiently active", 0:"Not classified"})
df['ACTIN23_'] = df['ACTIN23_'].replace({1:"Active", 2:"Insufficiently active", 0:"Not classified"})
df['_PACAT3'] = df['_PACAT3'].replace({1:"Highly active", 2:"Active", 3:"Insufficiently active", 4:"Inactive", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_PAINDX3'] = df['_PAINDX3'].replace({1:"Meets Guidelines", 2:"Does not meet", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_PA30023'] = df['_PA30023'].replace({1:"Met Both", 2:"Not Met", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_PASTRNG'] = df['_PASTRNG'].replace({1:"Met", 2:"Not met", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_PAREC3'] = df['_PAREC3'].replace({1:"Met Both", 2:"Met Aerobic only", 3:"Met strengthening only", 4:"Met neither", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_MICHD'] = df['_MICHD'].replace({1:"Reported", 2:"Not Reported"})
df['_CASTHM1'] = df['_CASTHM1'].replace({1:"Current", 2:"Former", 3:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_ASTHMS1'] = df['_ASTHMS1'].replace({1:"Current", 2:"Former", 3:"Never", 7:"Don't Know / Not Sure", 9:"Refused"})
df['_DRDXAR2'] = df['_DRDXAR2'].replace({1:"Diagnosed", 2:"Not Diagnosed"})
df['_RACE'] = df['_RACE'].replace({1:"White NH", 2:"Black NH", 3:"AI/AN NH", 4:"Asian NH", 5:"NH PI", 6:"Other NH", 7:"Multiracial NH", 8:"Hispanic", 9:"Refused"})
df['_RACEG21'] = df['_RACEG21'].replace({1:"White NH", 2:"Non-white/Hispanic", 9:"Refused"})
df['_RACEGR3'] = df['_RACEGR3'].replace({1:"White NH", 2:"Black NH", 3:"Other NH", 4:"Multiracial NH", 5:"Hispanic", 9:"refused"})
df['_RACEPRV'] = df['_RACEPRV'].replace({1:"White NH", 2:"Black NH", 3:"AI/AN NH", 4:"Asian NH", 5:"NH PI", 6:"Other NH", 7:"Multiracial NH", 8:"Hispanic", 9:"Refused"})
df['_SEX'] = df['_SEX'].replace({1:"Male", 2:"Female"})
df['_AGEG5YR'] = df['_AGEG5YR'].replace({1:"18-24", 2:"25-29", 3:"30-34", 4:"35-39", 5:"40-44", 6:"45-49", 7:"50-54", 8:"55-59", 9:"60-64", 10:"65-69", 11:"70-74", 12:"75-79", 13:"80+", 14:"Don't know"})
df['_AGE65YR'] = df['_AGE65YR'].replace({1:"18-64", 2:"65+", 3:"Don't know"})
df['_AGE_G'] = df['_AGE_G'].replace({1:"18-24", 2:"25-34", 3:"35-44", 4:"45-54", 5:"55-64", 6:"65+"})
df['_BMI5CAT'] = df['_BMI5CAT'].replace({1:"Underweight < 18.5", 2:"Normal 18.5-24.9", 3:"Overweight 25.0-29.9", 4:"Obese 30.0+"})
df['_CHLDCNT'] = df['_CHLDCNT'].replace({1:"No children", 2:"One child", 3:"Two children", 4:"Three children", 5:"Four children", 6:"Five+ children", 9:"Don't know"})
df['_EDUCAG'] = df['_EDUCAG'].replace({1:"Did not graduate", 2:"Graduated HS", 3:"Attended College", 4:"Graduated from college", 9:"Don't know"})
df['_INCOMG1'] = df['_INCOMG1'].replace({1:"<15K", 2:"15K-<25K", 3:"25K-<35K", 4:"35K-<50K", 5:"50K-<100K", 6:"100K-<200K", 7:"200K+", 9:"Don't know"})
df['_SMOKER3'] = df['_SMOKER3'].replace({1:"Current daily smoker", 2:"Current some days", 3:"Former smoker", 4:"Never smoked", 9:"Don't know"})
df['_CURECI2'] = df['_CURECI2'].replace({1:"Currently daily", 2:"Current some days", 3:"Not at all", 4:"Never used", 9:"Don't know"})
df['_RFSEAT2'] = df['_RFSEAT2'].replace({1:"Always", 2:"Not always", 9:"Don't know"})
df['_RFSEAT3'] = df['_RFSEAT3'].replace({1:"Always", 2:"Not always", 9:"Don't know"})

df[cols5].fillna("Not asked or missing", inplace=True)

/tmp/ipykernel_10339/1948895842.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not asked or missing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[cols5].fillna("Not asked or missing", inplace=True)
/tmp/ipykernel_10339/1948895842.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols5].fillna("Not asked or missing", inplace=True)

In [18]:
# handling numeric columns
num1 = ['NUMHHOL4', 'CSRVCTL2', 'ACEADSAF', 'ACEADNED', 'COVIDNU2', 'RRCOGNT2']

num2 = ['NUMADULT', 'HHADULT', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS1', 'CHILDREN', 'FALL12MN', 'FALLINJ5', 'AVEDRNK3', 'DRNK3GE5', 'MAXDRNKS', 'DRNKDRI2',
        'CHKHEMO3', 'CSRVDOC1', 'MARIJAN1', 'HPVADSHT', '_AGE80', 'HTIN4', 'DROCDY4_']

num3 = ['LCSFIRST', 'LCSLAST', 'LCSNUMCG']

num4 = ['FC601_', 'MAXVO21_' ]

for i in num1:
  df[i] = df[i].replace({7:0, 8:0, 9:0})

for i in num2:
  df[i] = df[i].replace({77:0, 88:0, 99:0})

for i in num3:
  df[i] = df[i].replace({777:0, 888:0, 999:0})

for i in num4:
  df[i] = df[i].replace({99900:0})

df[cols6].fillna(0, inplace=True)

/tmp/ipykernel_10339/365759520.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols6].fillna(0, inplace=True)

In [19]:
df.info(max_cols=500)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 309 columns):
 #    Column    Non-Null Count   Dtype
---   ------    --------------   -----
 0    _STATE    433323 non-null  float64
 1    DISPCODE  433323 non-null  object
 2    STATERE1  88345 non-null   object
 3    LADULT1   88345 non-null   object
 4    NUMADULT  88330 non-null   float64
 5    LNDSXBRT  169 non-null     float64
 6    SAFETIME  344978 non-null  object
 7    CADULT1   344978 non-null  object
 8    CELSXBRT  2578 non-null    float64
 9    CSTATE1   344968 non-null  object
 10   HHADULT   344974 non-null  float64
 11   SEXVAR    433323 non-null  object
 12   GENHLTH   433319 non-null  object
 13   PHYSHLTH  433320 non-null  float64
 14   MENTHLTH  433320 non-null  float64
 15   POORHLTH  252170 non-null  float64
 16   PRIMINS1  433318 non-null  float64
 17   PERSDOC3  433320 non-null  object
 18   MEDCOST1  433321 non-null  object
 19   CHECKUP1  433321 non-null  object
 20   EXERANY2  433321 non-null  object
 21   EXRACT12  325227 non-null  float64
 22   EXEROFT1  323041 non-null  float64
 23   EXERHMM1  323039 non-null  float64
 24   EXRACT22  323040 non-null  float64
 25   EXEROFT2  228757 non-null  float64
 26   EXERHMM2  228757 non-null  float64
 27   STRENGTH  433319 non-null  float64
 28   BPHIGH6   433320 non-null  object
 29   BPMEDS1   176222 non-null  object
 30   CHOLCHK3  433320 non-null  object
 31   TOLDHI3   381511 non-null  object
 32   CHOLMED3  379883 non-null  object
 33   CVDINFR4  433320 non-null  object
 34   CVDCRHD4  433320 non-null  object
 35   CVDSTRK3  433319 non-null  object
 36   ASTHMA3   433320 non-null  object
 37   ASTHNOW   64366 non-null   object
 38   CHCSCNC1  433320 non-null  object
 39   CHCOCNC1  433320 non-null  object
 40   CHCCOPD3  433320 non-null  object
 41   ADDEPEV3  433320 non-null  object
 42   CHCKDNY2  433320 non-null  object
 43   HAVARTH4  433319 non-null  object
 44   DIABETE4  433318 non-null  object
 45   DIABAGE4  59786 non-null   float64
 46   MARITAL   433316 non-null  object
 47   EDUCA     433314 non-null  object
 48   RENTHOM1  433315 non-null  object
 49   NUMHHOL4  88345 non-null   float64
 50   CPDEMO1C  433278 non-null  float64
 51   VETERAN3  432104 non-null  object
 52   EMPLOY1   430355 non-null  object
 53   CHILDREN  428231 non-null  float64
 54   INCOME3   425248 non-null  object
 55   PREGNANT  76208 non-null   object
 56   WEIGHT2   422712 non-null  float64
 57   HEIGHT3   421674 non-null  float64
 58   DEAF      420248 non-null  object
 59   BLIND     419243 non-null  object
 60   DECIDE    418184 non-null  object
 61   DIFFWALK  417177 non-null  object
 62   DIFFDRES  416454 non-null  object
 63   DIFFALON  415463 non-null  object
 64   FALL12MN  292496 non-null  float64
 65   FALLINJ5  77739 non-null   float64
 66   SMOKE100  413649 non-null  object
 67   SMOKDAY2  158639 non-null  object
 68   USENOW3   412886 non-null  object
 69   ECIGNOW2  411856 non-null  object
 70   ALCDAY4   407879 non-null  float64
 71   AVEDRNK3  212126 non-null  float64
 72   DRNK3GE5  211689 non-null  float64
 73   MAXDRNKS  211286 non-null  float64
 74   FLUSHOT7  405572 non-null  object
 75   FLSHTMY3  196982 non-null  float64
 76   PNEUVAC4  404573 non-null  object
 77   SHINGLE2  256598 non-null  object
 78   HIVTST7   403710 non-null  object
 79   HIVTSTD3  133265 non-null  float64
 80   SEATBELT  402545 non-null  object
 81   DRNKDRI2  213005 non-null  float64
 82   COVIDPO1  401308 non-null  object
 83   COVIDSM1  201017 non-null  object
 84   COVIDACT  27036 non-null   object
 85   DIABTYPE  24275 non-null   object
 86   INSULIN1  24268 non-null   object
 87   CHKHEMO3  24260 non-null   float64
 88   EYEEXAM1  24253 non-null   object
 89   FEETSORE  24238 non-null   object
 90   ARTHEXER  23323 non-null   object
 91   ARTHEDU   23296 non-null   object
 92   LMTJOIN3  23262 non-null   object
 93   ARTHDIS2  23213 non-null   float64
 94   JOINPAI2  23152 non-null   float64
 95   LCSFIRST  8541 non-null    float64
 96   LCSLAST   6748 non-null    float64
 97   LCSNUMCG  8199 non-null    float64
 98   LCSCTSC1  24095 non-null   object
 99   LCSSCNCR  10272 non-null   object
 100  LCSCTWHN  1960 non-null    float64
 101  HADMAM    1093 non-null    object
 102  HOWLONG   914 non-null     float64
 103  CERVSCRN  1089 non-null    object
 104  CRVCLPAP  585 non-null     object
 105  CRVCLHPV  583 non-null     object
 106  HADHYST2  1083 non-null    object
 107  PSATEST1  29527 non-null   object
 108  PSATIME1  16246 non-null   float64
 109  PSASUGS1  16202 non-null   float64
 110  HADSIGM4  10639 non-null   object
 111  COLNSIGM  7657 non-null    float64
 112  COLNTES1  7449 non-null    float64
 113  SIGMTES1  1226 non-null    float64
 114  LASTSIG4  146 non-null     float64
 115  COLNCNCR  10612 non-null   object
 116  VIRCOLO1  2598 non-null    object
 117  VCLNTES2  340 non-null     float64
 118  SMALSTOL  2595 non-null    object
 119  STOLTEST  2161 non-null    float64
 120  STOOLDN2  2587 non-null    float64
 121  BLDSTFIT  512 non-null     object
 122  CNCRDIFF  17161 non-null   float64
 123  CNCRAGE   16629 non-null   float64
 124  CNCRTYP2  16606 non-null   float64
 125  CSRVDOC1  1808 non-null    float64
 126  CSRVSUM   1807 non-null    object
 127  CSRVRTRN  1805 non-null    object
 128  CSRVINST  1360 non-null    object
 129  CSRVINSR  1799 non-null    object
 130  CSRVDEIN  1797 non-null    object
 131  CSRVCLIN  1795 non-null    object
 132  CSRVPAIN  2773 non-null    object
 133  CSRVCTL2  222 non-null     float64
 134  CIMEMLO1  135909 non-null  object
 135  CDWORRY   22483 non-null   float64
 136  CDDISCU1  22470 non-null   object
 137  CDHOUS1   22443 non-null   float64
 138  CDSOCIA1  22410 non-null   float64
 139  CAREGIV1  50811 non-null   object
 140  CRGVREL4  11483 non-null   float64
 141  CRGVLNG1  11457 non-null   object
 142  CRGVHRS1  11424 non-null   object
 143  CRGVPRB3  11397 non-null   float64
 144  CRGVALZD  10081 non-null   object
 145  CRGVPER1  11347 non-null   object
 146  CRGVHOU1  11336 non-null   object
 147  CRGVEXPT  39153 non-null   float64
 148  LASTSMK2  50984 non-null   float64
 149  STOPSMK2  20729 non-null   object
 150  MENTCIGS  26214 non-null   object
 151  MENTECIG  12455 non-null   object
 152  HEATTBCO  237914 non-null  object
 153  FIREARM5  81310 non-null   object
 154  GUNLOAD   30177 non-null   object
 155  LOADULK2  10155 non-null   object
 156  HASYMP1   10522 non-null   object
 157  HASYMP2   10507 non-null   object
 158  HASYMP3   10501 non-null   object
 159  HASYMP4   10493 non-null   object
 160  HASYMP5   10484 non-null   object
 161  HASYMP6   10475 non-null   object
 162  STRSYMP1  10438 non-null   object
 163  STRSYMP2  10424 non-null   object
 164  STRSYMP3  10416 non-null   object
 165  STRSYMP4  10403 non-null   object
 166  STRSYMP5  10391 non-null   object
 167  STRSYMP6  10375 non-null   object
 168  FIRSTAID  10359 non-null   float64
 169  ASPIRIN   25845 non-null   float64
 170  BIRTHSEX  105230 non-null  float64
 171  SOMALE    135790 non-null  object
 172  SOFEMALE  153467 non-null  object
 173  TRNSGNDR  289143 non-null  float64
 174  MARIJAN1  88613 non-null   float64
 175  MARJSMOK  11440 non-null   object
 176  MARJEAT   11433 non-null   object
 177  MARJVAPE  11425 non-null   object
 178  MARJDAB   11413 non-null   object
 179  MARJOTHR  11405 non-null   object
 180  USEMRJN4  4754 non-null    object
 181  ACEDEPRS  56040 non-null   object
 182  ACEDRINK  55939 non-null   object
 183  ACEDRUGS  55891 non-null   object
 184  ACEPRISN  55845 non-null   object
 185  ACEDIVRC  55808 non-null   object
 186  ACEPUNCH  55758 non-null   object
 187  ACEHURT1  55687 non-null   object
 188  ACESWEAR  55621 non-null   object
 189  ACEADSAF  55303 non-null   float64
 190  ACEADNED  55224 non-null   float64
 191  IMFVPLA4  4063 non-null    float64
 192  HPVADVC4  8902 non-null    object
 193  HPVADSHT  2292 non-null    float64
 194  TETANUS1  12840 non-null   object
 195  COVIDVA1  131896 non-null  object
 196  COVIDNU2  110754 non-null  float64
 197  LSATISFY  226676 non-null  object
 198  EMTSUPRT  226318 non-null  object
 199  SDLONELY  225998 non-null  object
 200  SDHEMPLY  225739 non-null  object
 201  FOODSTMP  225475 non-null  object
 202  SDHFOOD1  225129 non-null  object
 203  SDHBILLS  224861 non-null  float64
 204  SDHUTILS  224624 non-null  object
 205  SDHTRNSP  224266 non-null  object
 206  SDHSTRE1  223493 non-null  object
 207  RRCLASS3  142505 non-null  float64
 208  RRCOGNT2  142164 non-null  float64
 209  RRTREAT   141806 non-null  float64
 210  RRATWRK2  70209 non-null   float64
 211  RRHCARE4  141333 non-null  float64
 212  RRPHYSM2  141022 non-null  float64
 213  RCSGEND1  49434 non-null   float64
 214  RCSXBRTH  2634 non-null    float64
 215  RCSRLTN2  49024 non-null   float64
 216  CASTHDX2  47624 non-null   object
 217  CASTHNO2  4749 non-null    object
 218  QSTVER    433323 non-null  float64
 219  QSTLANG   433323 non-null  object
 220  _METSTAT  425000 non-null  object
 221  _URBSTAT  425000 non-null  object
 222  MSCODE    85527 non-null   object
 223  _STSTR    433323 non-null  float64
 224  _STRWT    433323 non-null  float64
 225  _RAWRAKE  433323 non-null  float64
 226  _WT2RAKE  433323 non-null  float64
 227  _IMPRACE  433323 non-null  object
 228  _CHISPNC  277030 non-null  object
 229  _CRACE1   51210 non-null   float64
 230  CAGEG     41925 non-null   float64
 231  _CLLCPWT  49541 non-null   float64
 232  _DUALUSE  433323 non-null  object
 233  _DUALCOR  144162 non-null  float64
 234  _LLCPWT2  433323 non-null  float64
 235  _LLCPWT   433323 non-null  float64
 236  _RFHLTH   433323 non-null  object
 237  _PHYS14D  433323 non-null  object
 238  _MENT14D  433323 non-null  object
 239  _HLTHPL1  433323 non-null  object
 240  _HCVU653  433323 non-null  object
 241  _TOTINDA  433323 non-null  object
 242  METVL12_  323041 non-null  float64
 243  METVL22_  228757 non-null  float64
 244  MAXVO21_  433323 non-null  float64
 245  FC601_    433323 non-null  float64
 246  ACTIN13_  317417 non-null  object
 247  ACTIN23_  225086 non-null  object
 248  PADUR1_   315638 non-null  float64
 249  PADUR2_   223535 non-null  float64
 250  PAFREQ1_  316148 non-null  float64
 251  PAFREQ2_  224522 non-null  float64
 252  _MINAC12  310832 non-null  float64
 253  _MINAC22  310052 non-null  float64
 254  STRFREQ_  419150 non-null  float64
 255  PAMISS3_  433323 non-null  float64
 256  PAMIN13_  305711 non-null  float64
 257  PAMIN23_  217736 non-null  float64
 258  PA3MIN_   310074 non-null  float64
 259  PAVIG13_  312636 non-null  float64
 260  PAVIG23_  221455 non-null  float64
 261  PA3VIGM_  314603 non-null  float64
 262  _PACAT3   433323 non-null  object
 263  _PAINDX3  433323 non-null  object
 264  _PA30023  433323 non-null  object
 265  _PASTRNG  433323 non-null  object
 266  _PAREC3   433323 non-null  object
 267  _PASTAE3  433323 non-null  object
 268  _RFHYPE6  433323 non-null  object
 269  _RFCHOL3  381512 non-null  object
 270  _MICHD    428738 non-null  object
 271  _LTASTH1  433323 non-null  object
 272  _CASTHM1  433323 non-null  object
 273  _ASTHMS1  433323 non-null  object
 274  _DRDXAR2  430763 non-null  object
 275  _MRACE1   433069 non-null  float64
 276  _HISPANC  433323 non-null  object
 277  _RACE     433237 non-null  object
 278  _RACEG21  433237 non-null  object
 279  _RACEGR3  433237 non-null  object
 280  _RACEPRV  433237 non-null  object
 281  _SEX      433323 non-null  object
 282  _AGEG5YR  433323 non-null  object
 283  _AGE65YR  433323 non-null  object
 284  _AGE80    433323 non-null  float64
 285  _AGE_G    433323 non-null  object
 286  HTIN4     405324 non-null  float64
 287  HTM4      411182 non-null  float64
 288  WTKG3     399172 non-null  float64
 289  _BMI5     392788 non-null  float64
 290  _BMI5CAT  392788 non-null  object
 291  _RFBMI5   433323 non-null  object
 292  _CHLDCNT  433323 non-null  object
 293  _EDUCAG   433323 non-null  object
 294  _INCOMG1  433323 non-null  object
 295  _SMOKER3  433323 non-null  object
 296  _RFSMOK3  433323 non-null  object
 297  _CURECI2  433323 non-null  object
 298  DRNKANY6  433323 non-null  object
 299  DROCDY4_  433323 non-null  float64
 300  _RFBING6  433323 non-null  object
 301  _DRNKWK2  433323 non-null  float64
 302  _RFDRHV8  433323 non-null  object
 303  _FLSHOT7  170823 non-null  object
 304  _PNEUMO3  170823 non-null  object
 305  _AIDTST4  403710 non-null  object
 306  _RFSEAT2  433323 non-null  object
 307  _RFSEAT3  433323 non-null  object
 308  _DRNKDRV  433323 non-null  object
dtypes: float64(117), object(192)
memory usage: 1021.6+ MB

In [20]:
# dividing columns into numerical and categorical types

cat = df.select_dtypes(include=['object', 'category']).columns.tolist()
num = df.select_dtypes(include=['number']).columns.tolist()

print("****Categorical columns*********")
print(cat)
print("****Numerical columns*********")
print(num)

****Categorical columns*********
['DISPCODE', 'STATERE1', 'LADULT1', 'SAFETIME', 'CADULT1', 'CSTATE1', 'SEXVAR', 'GENHLTH', 'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2', 'BPHIGH6', 'BPMEDS1', 'CHOLCHK3', 'TOLDHI3', 'CHOLMED3', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNC1', 'CHCOCNC1', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'HAVARTH4', 'DIABETE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'VETERAN3', 'EMPLOY1', 'INCOME3', 'PREGNANT', 'DEAF', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'SMOKDAY2', 'USENOW3', 'ECIGNOW2', 'FLUSHOT7', 'PNEUVAC4', 'SHINGLE2', 'HIVTST7', 'SEATBELT', 'COVIDPO1', 'COVIDSM1', 'COVIDACT', 'DIABTYPE', 'INSULIN1', 'EYEEXAM1', 'FEETSORE', 'ARTHEXER', 'ARTHEDU', 'LMTJOIN3', 'LCSCTSC1', 'LCSSCNCR', 'HADMAM', 'CERVSCRN', 'CRVCLPAP', 'CRVCLHPV', 'HADHYST2', 'PSATEST1', 'HADSIGM4', 'COLNCNCR', 'VIRCOLO1', 'SMALSTOL', 'BLDSTFIT', 'CSRVSUM', 'CSRVRTRN', 'CSRVINST', 'CSRVINSR', 'CSRVDEIN', 'CSRVCLIN', 'CSRVPAIN', 'CIMEMLO1', 'CDDISCU1', 'CAREGIV1', 'CRGVLNG1', 'CRGVHRS1', 'CRGVALZD', 'CRGVPER1', 'CRGVHOU1', 'STOPSMK2', 'MENTCIGS', 'MENTECIG', 'HEATTBCO', 'FIREARM5', 'GUNLOAD', 'LOADULK2', 'HASYMP1', 'HASYMP2', 'HASYMP3', 'HASYMP4', 'HASYMP5', 'HASYMP6', 'STRSYMP1', 'STRSYMP2', 'STRSYMP3', 'STRSYMP4', 'STRSYMP5', 'STRSYMP6', 'SOMALE', 'SOFEMALE', 'MARJSMOK', 'MARJEAT', 'MARJVAPE', 'MARJDAB', 'MARJOTHR', 'USEMRJN4', 'ACEDEPRS', 'ACEDRINK', 'ACEDRUGS', 'ACEPRISN', 'ACEDIVRC', 'ACEPUNCH', 'ACEHURT1', 'ACESWEAR', 'HPVADVC4', 'TETANUS1', 'COVIDVA1', 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1', 'SDHUTILS', 'SDHTRNSP', 'SDHSTRE1', 'CASTHDX2', 'CASTHNO2', 'QSTLANG', '_METSTAT', '_URBSTAT', 'MSCODE', '_IMPRACE', '_CHISPNC', '_DUALUSE', '_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL1', '_HCVU653', '_TOTINDA', 'ACTIN13_', 'ACTIN23_', '_PACAT3', '_PAINDX3', '_PA30023', '_PASTRNG', '_PAREC3', '_PASTAE3', '_RFHYPE6', '_RFCHOL3', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_HISPANC', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV', '_SEX', '_AGEG5YR', '_AGE65YR', '_AGE_G', '_BMI5CAT', '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG1', '_SMOKER3', '_RFSMOK3', '_CURECI2', 'DRNKANY6', '_RFBING6', '_RFDRHV8', '_FLSHOT7', '_PNEUMO3', '_AIDTST4', '_RFSEAT2', '_RFSEAT3', '_DRNKDRV']
****Numerical columns*********
['_STATE', 'NUMADULT', 'LNDSXBRT', 'CELSXBRT', 'HHADULT', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS1', 'EXRACT12', 'EXEROFT1', 'EXERHMM1', 'EXRACT22', 'EXEROFT2', 'EXERHMM2', 'STRENGTH', 'DIABAGE4', 'NUMHHOL4', 'CPDEMO1C', 'CHILDREN', 'WEIGHT2', 'HEIGHT3', 'FALL12MN', 'FALLINJ5', 'ALCDAY4', 'AVEDRNK3', 'DRNK3GE5', 'MAXDRNKS', 'FLSHTMY3', 'HIVTSTD3', 'DRNKDRI2', 'CHKHEMO3', 'ARTHDIS2', 'JOINPAI2', 'LCSFIRST', 'LCSLAST', 'LCSNUMCG', 'LCSCTWHN', 'HOWLONG', 'PSATIME1', 'PSASUGS1', 'COLNSIGM', 'COLNTES1', 'SIGMTES1', 'LASTSIG4', 'VCLNTES2', 'STOLTEST', 'STOOLDN2', 'CNCRDIFF', 'CNCRAGE', 'CNCRTYP2', 'CSRVDOC1', 'CSRVCTL2', 'CDWORRY', 'CDHOUS1', 'CDSOCIA1', 'CRGVREL4', 'CRGVPRB3', 'CRGVEXPT', 'LASTSMK2', 'FIRSTAID', 'ASPIRIN', 'BIRTHSEX', 'TRNSGNDR', 'MARIJAN1', 'ACEADSAF', 'ACEADNED', 'IMFVPLA4', 'HPVADSHT', 'COVIDNU2', 'SDHBILLS', 'RRCLASS3', 'RRCOGNT2', 'RRTREAT', 'RRATWRK2', 'RRHCARE4', 'RRPHYSM2', 'RCSGEND1', 'RCSXBRTH', 'RCSRLTN2', 'QSTVER', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_CRACE1', 'CAGEG', '_CLLCPWT', '_DUALCOR', '_LLCPWT2', '_LLCPWT', 'METVL12_', 'METVL22_', 'MAXVO21_', 'FC601_', 'PADUR1_', 'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', '_MINAC12', '_MINAC22', 'STRFREQ_', 'PAMISS3_', 'PAMIN13_', 'PAMIN23_', 'PA3MIN_', 'PAVIG13_', 'PAVIG23_', 'PA3VIGM_', '_MRACE1', '_AGE80', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', 'DROCDY4_', '_DRNKWK2']

## Stats Analysis

In [21]:
df[num].describe().T

,count,mean,std,min,25%,50%,75%,max
_STATE,433323.0,30.486898,16.670560,1.000000e+00,1.800000e+01,2.900000e+01,45.000000,78.000000
NUMADULT,88330.0,1.755723,0.839928,0.000000e+00,1.000000e+00,2.000000e+00,2.000000,18.000000
LNDSXBRT,169.0,1.497041,0.501477,1.000000e+00,1.000000e+00,1.000000e+00,2.000000,2.000000
CELSXBRT,2578.0,1.501939,0.500093,1.000000e+00,1.000000e+00,2.000000e+00,2.000000,2.000000
HHADULT,344974.0,2.127076,1.113132,0.000000e+00,1.000000e+00,2.000000e+00,2.000000,52.000000
PHYSHLTH,433320.0,4.371054,8.744814,0.000000e+00,0.000000e+00,0.000000e+00,3.000000,30.000000
MENTHLTH,433320.0,4.276862,8.263804,0.000000e+00,0.000000e+00,0.000000e+00,4.000000,30.000000
POORHLTH,252170.0,5.272443,9.008101,0.000000e+00,0.000000e+00,0.000000e+00,5.000000,30.000000
PRIMINS1,433318.0,2.568317,2.309257,0.000000e+00,1.000000e+00,2.000000e+00,3.000000,10.000000
EXRACT12,325227.0,4.241213,7.517496,1.000000e+00,1.000000e+00,1.000000e+00,7.000000,99.000000
EXEROFT1,323041.0,154.081148,110.669016,1.010000e+02,1.030000e+02,1.050000e+02,207.000000,999.000000
EXERHMM1,323039.0,129.516322,169.698696,1.000000e+00,3.000000e+01,1.000000e+02,130.000000,999.000000
EXRACT22,323040.0,29.835491,37.237778,1.000000e+00,3.000000e+00,9.000000e+00,88.000000,99.000000
EXEROFT2,228757.0,152.756619,104.069296,1.010000e+02,1.020000e+02,1.050000e+02,204.000000,999.000000
EXERHMM2,228757.0,139.719633,181.746530,1.000000e+00,3.000000e+01,1.000000e+02,200.000000,999.000000
STRENGTH,433319.0,505.888565,372.944256,1.010000e+02,1.050000e+02,2.300000e+02,888.000000,999.000000
DIABAGE4,59786.0,53.398505,19.210971,1.000000e+00,4.000000e+01,5.200000e+01,62.000000,99.000000
NUMHHOL4,88345.0,1.901228,0.323652,0.000000e+00,2.000000e+00,2.000000e+00,2.000000,2.000000
CPDEMO1C,433278.0,1.367711,1.418734,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,9.000000
CHILDREN,428231.0,0.473978,1.026931,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,81.000000
WEIGHT2,422712.0,757.960056,2224.967510,5.000000e+01,1.500000e+02,1.800000e+02,220.000000,9999.000000
HEIGHT3,421674.0,853.547046,1670.598628,2.000000e+02,5.040000e+02,5.070000e+02,511.000000,9999.000000
FALL12MN,292496.0,0.766691,3.181951,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,76.000000
FALLINJ5,77739.0,0.750614,2.431537,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,76.000000
ALCDAY4,407879.0,514.303009,359.648989,1.010000e+02,2.010000e+02,2.300000e+02,888.000000,999.000000
AVEDRNK3,212126.0,2.145079,2.179883,0.000000e+00,1.000000e+00,2.000000e+00,2.000000,76.000000
DRNK3GE5,211689.0,1.154439,3.865793,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,76.000000
MAXDRNKS,211286.0,3.184863,3.313013,0.000000e+00,1.000000e+00,2.000000e+00,4.000000,76.000000
FLSHTMY3,196982.0,156620.123199,199873.079481,1.202200e+04,9.202300e+04,1.020220e+05,112022.000000,999999.000000
HIVTSTD3,133265.0,403148.349664,357442.883362,1.198500e+04,6.201800e+04,1.220100e+05,777777.000000,999999.000000
DRNKDRI2,213005.0,0.081838,1.013452,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,76.000000
CHKHEMO3,24260.0,3.453339,9.345431,0.000000e+00,1.000000e+00,2.000000e+00,4.000000,98.000000
ARTHDIS2,23213.0,1.890535,0.993102,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
JOINPAI2,23152.0,7.414478,14.498792,5.397605e-79,2.000000e+00,4.000000e+00,7.000000,99.000000
LCSFIRST,8541.0,17.130898,6.609301,0.000000e+00,1.500000e+01,1.700000e+01,20.000000,75.000000
LCSLAST,6748.0,36.149674,16.454647,0.000000e+00,2.500000e+01,3.500000e+01,48.000000,90.000000
LCSNUMCG,8199.0,13.531528,12.696399,0.000000e+00,5.000000e+00,1.000000e+01,20.000000,203.000000
LCSCTWHN,1960.0,2.555102,1.921381,1.000000e+00,1.000000e+00,2.000000e+00,4.000000,9.000000
HOWLONG,914.0,2.006565,1.545215,1.000000e+00,1.000000e+00,1.000000e+00,3.000000,7.000000
PSATIME1,16246.0,1.896405,1.553769,1.000000e+00,1.000000e+00,1.000000e+00,2.000000,9.000000
PSASUGS1,16202.0,2.034008,0.796041,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
COLNSIGM,7657.0,1.440643,1.097594,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,9.000000
COLNTES1,7449.0,2.888441,1.392606,1.000000e+00,2.000000e+00,3.000000e+00,4.000000,9.000000
SIGMTES1,1226.0,3.977977,1.812070,1.000000e+00,3.000000e+00,4.000000e+00,5.000000,9.000000
LASTSIG4,146.0,3.732877,2.198090,1.000000e+00,2.000000e+00,3.000000e+00,5.000000,7.000000
VCLNTES2,340.0,3.214706,1.762713,1.000000e+00,2.000000e+00,3.000000e+00,4.250000,9.000000
STOLTEST,2161.0,2.675613,1.762207,1.000000e+00,1.000000e+00,2.000000e+00,4.000000,7.000000
STOOLDN2,2587.0,1.938539,0.943334,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
CNCRDIFF,17161.0,1.475497,1.244895,1.000000e+00,1.000000e+00,1.000000e+00,2.000000,9.000000
CNCRAGE,16629.0,58.916231,17.709725,1.000000e+00,4.900000e+01,6.000000e+01,70.000000,99.000000
CNCRTYP2,16606.0,19.115982,12.439809,1.000000e+00,1.300000e+01,2.000000e+01,23.000000,99.000000
CSRVDOC1,1808.0,4.564712,3.022735,0.000000e+00,2.000000e+00,5.000000e+00,6.000000,10.000000
CSRVCTL2,222.0,2.000000,1.195769,0.000000e+00,1.000000e+00,2.000000e+00,3.000000,4.000000
CDWORRY,22483.0,1.481297,0.709740,1.000000e+00,1.000000e+00,1.000000e+00,2.000000,9.000000
CDHOUS1,22443.0,1.698258,0.649687,1.000000e+00,1.000000e+00,2.000000e+00,2.000000,9.000000
CDSOCIA1,22410.0,1.850022,0.791960,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
CRGVREL4,11483.0,8.589219,11.382647,1.000000e+00,2.000000e+00,6.000000e+00,14.000000,99.000000
CRGVPRB3,11397.0,14.639291,18.791993,1.000000e+00,6.000000e+00,1.300000e+01,15.000000,99.000000
CRGVEXPT,39153.0,2.195847,1.352492,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
LASTSMK2,50984.0,6.983524,7.732542,1.000000e+00,6.000000e+00,7.000000e+00,7.000000,99.000000
FIRSTAID,10359.0,2.967661,0.764394,1.000000e+00,3.000000e+00,3.000000e+00,3.000000,9.000000
ASPIRIN,25845.0,3.285665,1.278596,1.000000e+00,3.000000e+00,4.000000e+00,4.000000,9.000000
BIRTHSEX,105230.0,1.557227,0.628365,1.000000e+00,1.000000e+00,2.000000e+00,2.000000,9.000000
TRNSGNDR,289143.0,4.055350,0.585031,1.000000e+00,4.000000e+00,4.000000e+00,4.000000,9.000000
MARIJAN1,88613.0,2.126652,7.022627,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,30.000000
ACEADSAF,55303.0,4.427337,1.126575,0.000000e+00,4.000000e+00,5.000000e+00,5.000000,5.000000
ACEADNED,55224.0,4.670487,0.896717,0.000000e+00,5.000000e+00,5.000000e+00,5.000000,5.000000
IMFVPLA4,4063.0,4.622200,6.877150,1.000000e+00,1.000000e+00,5.000000e+00,5.000000,99.000000
HPVADSHT,2292.0,1.730803,1.171632,0.000000e+00,1.000000e+00,2.000000e+00,3.000000,10.000000
COVIDNU2,110754.0,3.065758,1.157596,0.000000e+00,2.000000e+00,3.000000e+00,4.000000,5.000000
SDHBILLS,224861.0,1.938491,0.504909,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
RRCLASS3,142505.0,3.408344,13.163430,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,99.000000
RRCOGNT2,142164.0,1.713113,1.357037,0.000000e+00,1.000000e+00,1.000000e+00,3.000000,6.000000
RRTREAT,141806.0,2.734236,1.682061,1.000000e+00,2.000000e+00,2.000000e+00,3.000000,9.000000
RRATWRK2,70209.0,2.379766,1.368939,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
RRHCARE4,141333.0,2.832148,1.795019,1.000000e+00,2.000000e+00,2.000000e+00,3.000000,9.000000
RRPHYSM2,141022.0,2.051169,0.737156,1.000000e+00,2.000000e+00,2.000000e+00,2.000000,9.000000
RCSGEND1,49434.0,1.868977,1.727310,1.000000e+00,1.000000e+00,2.000000e+00,2.000000,9.000000
RCSXBRTH,2634.0,8.313212,2.150138,1.000000e+00,9.000000e+00,9.000000e+00,9.000000,9.000000
RCSRLTN2,49024.0,1.737292,1.761459,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,9.000000
QSTVER,433323.0,18.520822,4.121691,1.000000e+01,2.000000e+01,2.000000e+01,21.000000,23.000000
_STSTR,433323.0,306723.635644,166704.068329,1.101100e+04,1.810810e+05,2.920810e+05,452041.000000,782029.000000
_STRWT,433323.0,39.565202,57.672312,3.184905e-01,8.595329e+00,2.544575e+01,47.013435,840.761894
_RAWRAKE,433323.0,1.146152,0.458582,3.333333e-01,1.000000e+00,1.000000e+00,1.000000,5.000000
_WT2RAKE,433323.0,42.074037,61.084251,1.469898e-01,1.011169e+01,2.714446e+01,48.273478,2000.973109
_CRACE1,51210.0,8.216598,23.554481,1.000000e+00,1.000000e+00,1.000000e+00,2.000000,99.000000
CAGEG,41925.0,2.566559,1.088507,1.000000e+00,2.000000e+00,3.000000e+00,3.000000,4.000000
_CLLCPWT,49541.0,925.858283,2070.911564,1.162012e+01,1.375689e+02,3.282914e+02,874.111740,42470.198778
_DUALCOR,144162.0,0.534621,0.192801,1.870853e-02,4.086264e-01,5.507481e-01,0.645494,0.981291
_LLCPWT2,433323.0,586.486351,882.658416,6.784071e+00,1.470496e+02,3.255510e+02,627.673708,23306.277105
_LLCPWT,433323.0,586.490514,1190.719872,1.591041e-01,1.033665e+02,2.582719e+02,604.551174,69785.820912
METVL12_,323041.0,38.480307,15.190303,5.397605e-79,3.500000e+01,3.500000e+01,45.000000,73.000000
METVL22_,228757.0,38.388076,18.059432,5.397605e-79,3.500000e+01,4.500000e+01,45.000000,73.000000
MAXVO21_,433323.0,2789.549793,951.426584,0.000000e+00,2.136000e+03,2.691000e+03,3468.000000,5010.000000
FC601_,433323.0,478.211747,163.108297,0.000000e+00,3.660000e+02,4.610000e+02,595.000000,859.000000
PADUR1_,315638.0,75.318840,79.524568,1.000000e+00,3.000000e+01,6.000000e+01,90.000000,599.000000
PADUR2_,223535.0,80.832943,89.215288,1.000000e+00,3.000000e+01,6.000000e+01,90.000000,599.000000
PAFREQ1_,316148.0,4272.262412,4268.053697,2.330000e+02,2.000000e+03,3.733000e+03,5833.000000,99000.000000
PAFREQ2_,224522.0,3399.995163,4255.096134,2.330000e+02,1.167000e+03,2.800000e+03,4667.000000,99000.000000
_MINAC12,310832.0,296.766787,680.856786,5.397605e-79,7.000000e+01,1.600000e+02,300.000000,59301.000000
_MINAC22,310052.0,182.932863,617.775296,5.397605e-79,5.397605e-79,5.300000e+01,168.000000,59301.000000
STRFREQ_,419150.0,1911.242997,3556.999432,5.397605e-79,5.397605e-79,4.670000e+02,3000.000000,99000.000000
PAMISS3_,433323.0,0.284114,0.641294,5.397605e-79,5.397605e-79,5.397605e-79,1.000000,9.000000
PAMIN13_,305711.0,398.330803,954.686619,5.397605e-79,9.000000e+01,2.000000e+02,420.000000,118602.000000
PAMIN23_,217736.0,347.321288,945.058668,5.397605e-79,4.600000e+01,1.200000e+02,336.000000,71280.000000
PA3MIN_,310074.0,636.617246,1322.466047,5.397605e-79,1.400000e+02,3.150000e+02,672.000000,118602.000000
PAVIG13_,312636.0,99.625955,401.167938,5.397605e-79,5.397605e-79,5.397605e-79,70.000000,59301.000000
PAVIG23_,221455.0,89.430214,366.725103,5.397605e-79,5.397605e-79,5.397605e-79,60.000000,35640.000000
PA3VIGM_,314603.0,161.954679,536.113211,5.397605e-79,5.397605e-79,5.397605e-79,144.000000,59301.000000
_MRACE1,433069.0,3.853506,14.348535,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,99.000000
_AGE80,433323.0,54.187027,18.959224,0.000000e+00,4.000000e+01,5.700000e+01,70.000000,80.000000
HTIN4,405324.0,66.740173,6.004546,0.000000e+00,6.400000e+01,6.700000e+01,70.000000,95.000000
HTM4,411182.0,170.253309,10.744241,9.100000e+01,1.630000e+02,1.700000e+02,178.000000,241.000000
WTKG3,399172.0,8288.646158,2133.894650,2.268000e+03,6.804000e+03,8.029000e+03,9435.000000,28400.000000
_BMI5,392788.0,2847.928783,654.197490,1.202000e+03,2.410000e+03,2.740000e+03,3162.000000,9984.000000
DROCDY4_,433323.0,77.456611,225.614794,0.000000e+00,5.397605e-79,3.000000e+00,29.000000,900.000000
_DRNKWK2,433323.0,7826.638676,26371.148838,5.397605e-79,5.397605e-79,4.700000e+01,400.000000,99900.000000

In [22]:
df[cat].describe().T

           count unique                     top    freq
DISPCODE  433323      2                Complete  356261
STATERE1   88345      2                     Yes   88344
LADULT1    88345      2                     Yes   88212
SAFETIME  344978      1                     Yes  344978
CADULT1   344978      1                     Yes  344978
CSTATE1   344968      2                     Yes  326473
SEXVAR    433323      2                  Female  229541
GENHLTH   433319      7                    Good  144209
PERSDOC3  433320      5           Yes, Only one  234388
MEDCOST1  433321      4                      No  394587
CHECKUP1  433321      7        Within past year  348057
EXERANY2  433321      4                     Yes  325227
BPHIGH6   433320      6                      No  247855
BPMEDS1   176222      4                     Yes  144089
CHOLCHK3  433320      8     Within past 2 years  307737
TOLDHI3   381511      4                      No  219333
CHOLMED3  379883      4                      No  254973
CVDINFR4  433320      4                      No  407304
CVDCRHD4  433320      4                      No  405638
CVDSTRK3  433319      4                      No  413499
ASTHMA3   433320      4                      No  367256
ASTHNOW    64366      4                     Yes   43949
CHCSCNC1  433320      4                      No  393826
CHCOCNC1  433320      4                      No  380431
CHCCOPD3  433320      4                      No  398160
ADDEPEV3  433320      4                      No  342587
CHCKDNY2  433320      4                      No  410876
HAVARTH4  433319      4                      No  287999
DIABETE4  433318      6                      No  358706
MARITAL   433316      7                 Married  222210
EDUCA     433314      7        College 4+ years  184867
RENTHOM1  433315      5                     Own  301956
VETERAN3  432104      4                      No  379749
EMPLOY1   430355      9      Employed for wages  177871
INCOME3   425248     13                 50K-75K   57896
PREGNANT   76208      4                      No   73626
DEAF      420248      4                      No  379796
BLIND     419243      4                      No  395423
DECIDE    418184      4                      No  365547
DIFFWALK  417177      4                      No  348452
DIFFDRES  416454      4                      No  399108
DIFFALON  415463      4                      No  381959
SMOKE100  413649      4                      No  251981
SMOKDAY2  158639      5              Not at all  113134
USENOW3   412886      5              Not at all  400228
ECIGNOW2  411856      6                Everyday  318696
FLUSHOT7  405572      4                      No  204711
PNEUVAC4  404573      4                      No  208403
SHINGLE2  256598      4                     Yes  126962
HIVTST7   403710      4                      No  249505
SEATBELT  402545      8                  Always  350207
COVIDPO1  401308      4                     Yes  201248
COVIDSM1  201017      4                      No  170893
COVIDACT   27036      5              Not at all   10698
DIABTYPE   24275      4                  Type 2   20069
INSULIN1   24268      4                      No   16347
EYEEXAM1   24253      7        Within past year   12216
FEETSORE   24238      4                      No   21888
ARTHEXER   23323      4                     Yes   14553
ARTHEDU    23296      4                      No   19692
LMTJOIN3   23262      4                      No   13207
LCSCTSC1   24095      4                      No   12852
LCSSCNCR   10272      4                      No    7774
HADMAM      1093      4                     Yes     916
CERVSCRN    1089      4                     Yes     585
CRVCLPAP     585      3                     Yes     524
CRVCLHPV     583      3                     Yes     218
HADHYST2    1083      4                      No     786
PSATEST1   29527      4                     Yes   16263
HADSIGM4   10639      4                     Yes    7659
COLNCNCR   10612      4                      No    7678
VIRCOLO1    2598      3                      No    2156
SMALSTOL    2595      3                     Yes    2166
BLDSTFIT     512      3                     Yes     338
CSRVSUM     1807      4                      No     870
CSRVRTRN    1805      4                     Yes    1362
CSRVINST    1360      4                     Yes     987
CSRVINSR    1799      4                     Yes    1708
CSRVDEIN    1797      4                      No    1688
CSRVCLIN    1795      4                      No    1686
CSRVPAIN    2773      4                      No    2520
CIMEMLO1  135909      4                      No  111530
CDDISCU1   22470      4                      No   12605
CAREGIV1   50811      5                      No   39022
CRGVLNG1   11457      7                5+ years    3464
CRGVHRS1   11424      6            Upto 8 hours    5398
CRGVALZD   10081      4                      No    8101
CRGVPER1   11347      4                      No    5664
CRGVHOU1   11336      4                     Yes    8847
STOPSMK2   20729      4                     Yes   10330
MENTCIGS   26214      4                      No   18019
MENTECIG   12455      4                      No    9007
HEATTBCO  237914      4                      No  209176
FIREARM5   81310      4                      No   44526
GUNLOAD    30177      4                      No   19097
LOADULK2   10155      4                     Yes    5494
HASYMP1    10522      4                     Yes    6471
HASYMP2    10507      4                     Yes    6759
HASYMP3    10501      4                     Yes    9584
HASYMP4    10493      4                      No    4860
HASYMP5    10484      4                     Yes    8796
HASYMP6    10475      4                     Yes    8608
STRSYMP1   10438      4                     Yes    9606
STRSYMP2   10424      4                     Yes    9861
STRSYMP3   10416      4                     Yes    7322
STRSYMP4   10403      4                      No    4088
STRSYMP5   10391      4                     Yes    8947
STRSYMP6   10375      4                     Yes    6673
SOMALE    135790      6                Straight  123225
SOFEMALE  153467      6                Straight  135763
MARJSMOK   11440      4                     Yes    8439
MARJEAT    11433      4                      No    6269
MARJVAPE   11425      4                      No    8514
MARJDAB    11413      4                      No   10149
MARJOTHR   11405      4                      No   10559
USEMRJN4    4754      6                 Medical    2702
ACEDEPRS   56040      4                      No   44138
ACEDRINK   55939      4                      No   41766
ACEDRUGS   55891      4                      No   49240
ACEPRISN   55845      4                      No   51195
ACEDIVRC   55808      5                      No   38883
ACEPUNCH   55758      5                   Never   45101
ACEHURT1   55687      5                   Never   39912
ACESWEAR   55621      5                   Never   35496
HPVADVC4    8902      4                      No    5611
TETANUS1   12840      6                      No    4305
COVIDVA1  131896      4                     Yes  110817
LSATISFY  226676      6               Satisfied  111150
EMTSUPRT  226318      7                  Always  110198
SDLONELY  225998      7                   Never   89592
SDHEMPLY  225739      4                      No  203838
FOODSTMP  225475      4                      No  202882
SDHFOOD1  225129      7                   Never  179027
SDHUTILS  224624      4                      No  210190
SDHTRNSP  224266      4                      No  208950
SDHSTRE1  223493      7                   Never   84895
CASTHDX2   47624      4                      No   40379
CASTHNO2    4749      4                     Yes    3187
QSTLANG   433323      3                 English  414251
_METSTAT  425000      2      Metropolitian area  307756
_URBSTAT  425000      2                   Urban  369363
MSCODE     85527      4                 Non-MSA   30342
_IMPRACE  433323      6                White NH  321255
_CHISPNC  277030      3                 Refused  228715
_DUALUSE  433323      3                 Refused  289161
_RFHLTH   433323      3          Good or Better  349734
_PHYS14D  433323      4                  0 days  256565
_MENT14D  433323      4                  0 days  257026
_HLTHPL1  433323      3                     Yes  391946
_HCVU653  433323      3                     Yes  229958
_TOTINDA  433323      3            Had exercise  325227
ACTIN13_  317417      3                  Active  194526
ACTIN23_  225086      3                  Active  115942
_PACAT3   433323      5           Highly active  156975
_PAINDX3  433323      3        Meets Guidelines  230855
_PA30023  433323      3                 Not Met  191367
_PASTRNG  433323      3                 Not met  251216
_PAREC3   433323      5        Met Aerobic only  114995
_PASTAE3  433323      3                      No  253280
_RFHYPE6  433323      3                      No  255182
_RFCHOL3  381512      3                      No  219333
_MICHD    428738      2            Not Reported  392427
_LTASTH1  433323      3                     Yes  367256
_CASTHM1  433323      3                 Current  385732
_ASTHMS1  433323      4                   Never  367256
_DRDXAR2  430763      2           Not Diagnosed  287999
_HISPANC  433323      3                      No  384575
_RACE     433237      9                White NH  313067
_RACEG21  433237      3                White NH  313067
_RACEGR3  433237      6                White NH  313067
_RACEPRV  433237      8                White NH  321169
_SEX      433323      2                  Female  229523
_AGEG5YR  433323     14                   65-69   46099
_AGE65YR  433323      3                   18-64  262500
_AGE_G    433323      6                     65+  164955
_BMI5CAT  392788      4    Overweight 25.0-29.9  139615
_RFBMI5   433323      3                     Yes  269521
_CHLDCNT  433323      7             No children  319209
_EDUCAG   433323      5  Graduated from college  184867
_INCOMG1  433323      8               50K-<100K  107027
_SMOKER3  433323      5            Never smoked  251981
_RFSMOK3  433323      3                      No  365115
_CURECI2  433323      3         Currently daily  387806
DRNKANY6  433323      4                     Yes  212617
_RFBING6  433323      3                      No  346838
_RFDRHV8  433323      3                      No  376780
_FLSHOT7  170823      3                     Yes   99559
_PNEUMO3  170823      3                     Yes  107567
_AIDTST4  403710      3                      No  249505
_RFSEAT2  433323      3                  Always  379361
_RFSEAT3  433323      3                  Always  351080
_DRNKDRV  433323      3                 Refused  221590

In [23]:
# classifying numeric columns based on skewness
left_skew = []
right_skew = []

for i in num:
  if(df[i].skew() >0.5):
    right_skew.append(i)
  elif(df[i].skew() < -0.5):
    left_skew.append(i)

print("*********Left skewed columns************")
print(left_skew)
print("*********Right skewed columns***********")
print(right_skew)

*********Left skewed columns************
['NUMHHOL4', 'ASPIRIN', 'ACEADSAF', 'ACEADNED', 'RCSXBRTH', 'QSTVER', 'METVL22_', '_AGE80', 'HTIN4']
*********Right skewed columns***********
['NUMADULT', 'HHADULT', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS1', 'EXRACT12', 'EXEROFT1', 'EXERHMM1', 'EXRACT22', 'EXEROFT2', 'EXERHMM2', 'CPDEMO1C', 'CHILDREN', 'WEIGHT2', 'HEIGHT3', 'FALL12MN', 'FALLINJ5', 'AVEDRNK3', 'DRNK3GE5', 'MAXDRNKS', 'FLSHTMY3', 'DRNKDRI2', 'CHKHEMO3', 'ARTHDIS2', 'JOINPAI2', 'LCSFIRST', 'LCSNUMCG', 'LCSCTWHN', 'HOWLONG', 'PSATIME1', 'PSASUGS1', 'COLNSIGM', 'VCLNTES2', 'STOLTEST', 'STOOLDN2', 'CNCRDIFF', 'CNCRTYP2', 'CSRVDOC1', 'CDWORRY', 'CDHOUS1', 'CDSOCIA1', 'CRGVREL4', 'CRGVPRB3', 'CRGVEXPT', 'LASTSMK2', 'FIRSTAID', 'BIRTHSEX', 'TRNSGNDR', 'MARIJAN1', 'IMFVPLA4', 'SDHBILLS', 'RRCLASS3', 'RRCOGNT2', 'RRTREAT', 'RRATWRK2', 'RRHCARE4', 'RRPHYSM2', 'RCSGEND1', 'RCSRLTN2', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_CRACE1', '_CLLCPWT', '_LLCPWT2', '_LLCPWT', 'PADUR1_', 'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', '_MINAC12', '_MINAC22', 'STRFREQ_', 'PAMISS3_', 'PAMIN13_', 'PAMIN23_', 'PA3MIN_', 'PAVIG13_', 'PAVIG23_', 'PA3VIGM_', '_MRACE1', 'WTKG3', '_BMI5', 'DROCDY4_', '_DRNKWK2']

## Missing value treatment

In [24]:
# replacing the missing values in categorical columns with "Not asked or Missing"

df[cat] = df[cat].fillna("Not asked or missing")

In [25]:
# replacing the missing values in numerical columns with 0
df[num] = df[num].fillna(0)

In [26]:
# checking all the columns
df.info(max_cols=500)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 309 columns):
 #    Column    Non-Null Count   Dtype
---   ------    --------------   -----
 0    _STATE    433323 non-null  float64
 1    DISPCODE  433323 non-null  object
 2    STATERE1  433323 non-null  object
 3    LADULT1   433323 non-null  object
 4    NUMADULT  433323 non-null  float64
 5    LNDSXBRT  433323 non-null  float64
 6    SAFETIME  433323 non-null  object
 7    CADULT1   433323 non-null  object
 8    CELSXBRT  433323 non-null  float64
 9    CSTATE1   433323 non-null  object
 10   HHADULT   433323 non-null  float64
 11   SEXVAR    433323 non-null  object
 12   GENHLTH   433323 non-null  object
 13   PHYSHLTH  433323 non-null  float64
 14   MENTHLTH  433323 non-null  float64
 15   POORHLTH  433323 non-null  float64
 16   PRIMINS1  433323 non-null  float64
 17   PERSDOC3  433323 non-null  object
 18   MEDCOST1  433323 non-null  object
 19   CHECKUP1  433323 non-null  object
 20   EXERANY2  433323 non-null  object
 21   EXRACT12  433323 non-null  float64
 22   EXEROFT1  433323 non-null  float64
 23   EXERHMM1  433323 non-null  float64
 24   EXRACT22  433323 non-null  float64
 25   EXEROFT2  433323 non-null  float64
 26   EXERHMM2  433323 non-null  float64
 27   STRENGTH  433323 non-null  float64
 28   BPHIGH6   433323 non-null  object
 29   BPMEDS1   433323 non-null  object
 30   CHOLCHK3  433323 non-null  object
 31   TOLDHI3   433323 non-null  object
 32   CHOLMED3  433323 non-null  object
 33   CVDINFR4  433323 non-null  object
 34   CVDCRHD4  433323 non-null  object
 35   CVDSTRK3  433323 non-null  object
 36   ASTHMA3   433323 non-null  object
 37   ASTHNOW   433323 non-null  object
 38   CHCSCNC1  433323 non-null  object
 39   CHCOCNC1  433323 non-null  object
 40   CHCCOPD3  433323 non-null  object
 41   ADDEPEV3  433323 non-null  object
 42   CHCKDNY2  433323 non-null  object
 43   HAVARTH4  433323 non-null  object
 44   DIABETE4  433323 non-null  object
 45   DIABAGE4  433323 non-null  float64
 46   MARITAL   433323 non-null  object
 47   EDUCA     433323 non-null  object
 48   RENTHOM1  433323 non-null  object
 49   NUMHHOL4  433323 non-null  float64
 50   CPDEMO1C  433323 non-null  float64
 51   VETERAN3  433323 non-null  object
 52   EMPLOY1   433323 non-null  object
 53   CHILDREN  433323 non-null  float64
 54   INCOME3   433323 non-null  object
 55   PREGNANT  433323 non-null  object
 56   WEIGHT2   433323 non-null  float64
 57   HEIGHT3   433323 non-null  float64
 58   DEAF      433323 non-null  object
 59   BLIND     433323 non-null  object
 60   DECIDE    433323 non-null  object
 61   DIFFWALK  433323 non-null  object
 62   DIFFDRES  433323 non-null  object
 63   DIFFALON  433323 non-null  object
 64   FALL12MN  433323 non-null  float64
 65   FALLINJ5  433323 non-null  float64
 66   SMOKE100  433323 non-null  object
 67   SMOKDAY2  433323 non-null  object
 68   USENOW3   433323 non-null  object
 69   ECIGNOW2  433323 non-null  object
 70   ALCDAY4   433323 non-null  float64
 71   AVEDRNK3  433323 non-null  float64
 72   DRNK3GE5  433323 non-null  float64
 73   MAXDRNKS  433323 non-null  float64
 74   FLUSHOT7  433323 non-null  object
 75   FLSHTMY3  433323 non-null  float64
 76   PNEUVAC4  433323 non-null  object
 77   SHINGLE2  433323 non-null  object
 78   HIVTST7   433323 non-null  object
 79   HIVTSTD3  433323 non-null  float64
 80   SEATBELT  433323 non-null  object
 81   DRNKDRI2  433323 non-null  float64
 82   COVIDPO1  433323 non-null  object
 83   COVIDSM1  433323 non-null  object
 84   COVIDACT  433323 non-null  object
 85   DIABTYPE  433323 non-null  object
 86   INSULIN1  433323 non-null  object
 87   CHKHEMO3  433323 non-null  float64
 88   EYEEXAM1  433323 non-null  object
 89   FEETSORE  433323 non-null  object
 90   ARTHEXER  433323 non-null  object
 91   ARTHEDU   433323 non-null  object
 92   LMTJOIN3  433323 non-null  object
 93   ARTHDIS2  433323 non-null  float64
 94   JOINPAI2  433323 non-null  float64
 95   LCSFIRST  433323 non-null  float64
 96   LCSLAST   433323 non-null  float64
 97   LCSNUMCG  433323 non-null  float64
 98   LCSCTSC1  433323 non-null  object
 99   LCSSCNCR  433323 non-null  object
 100  LCSCTWHN  433323 non-null  float64
 101  HADMAM    433323 non-null  object
 102  HOWLONG   433323 non-null  float64
 103  CERVSCRN  433323 non-null  object
 104  CRVCLPAP  433323 non-null  object
 105  CRVCLHPV  433323 non-null  object
 106  HADHYST2  433323 non-null  object
 107  PSATEST1  433323 non-null  object
 108  PSATIME1  433323 non-null  float64
 109  PSASUGS1  433323 non-null  float64
 110  HADSIGM4  433323 non-null  object
 111  COLNSIGM  433323 non-null  float64
 112  COLNTES1  433323 non-null  float64
 113  SIGMTES1  433323 non-null  float64
 114  LASTSIG4  433323 non-null  float64
 115  COLNCNCR  433323 non-null  object
 116  VIRCOLO1  433323 non-null  object
 117  VCLNTES2  433323 non-null  float64
 118  SMALSTOL  433323 non-null  object
 119  STOLTEST  433323 non-null  float64
 120  STOOLDN2  433323 non-null  float64
 121  BLDSTFIT  433323 non-null  object
 122  CNCRDIFF  433323 non-null  float64
 123  CNCRAGE   433323 non-null  float64
 124  CNCRTYP2  433323 non-null  float64
 125  CSRVDOC1  433323 non-null  float64
 126  CSRVSUM   433323 non-null  object
 127  CSRVRTRN  433323 non-null  object
 128  CSRVINST  433323 non-null  object
 129  CSRVINSR  433323 non-null  object
 130  CSRVDEIN  433323 non-null  object
 131  CSRVCLIN  433323 non-null  object
 132  CSRVPAIN  433323 non-null  object
 133  CSRVCTL2  433323 non-null  float64
 134  CIMEMLO1  433323 non-null  object
 135  CDWORRY   433323 non-null  float64
 136  CDDISCU1  433323 non-null  object
 137  CDHOUS1   433323 non-null  float64
 138  CDSOCIA1  433323 non-null  float64
 139  CAREGIV1  433323 non-null  object
 140  CRGVREL4  433323 non-null  float64
 141  CRGVLNG1  433323 non-null  object
 142  CRGVHRS1  433323 non-null  object
 143  CRGVPRB3  433323 non-null  float64
 144  CRGVALZD  433323 non-null  object
 145  CRGVPER1  433323 non-null  object
 146  CRGVHOU1  433323 non-null  object
 147  CRGVEXPT  433323 non-null  float64
 148  LASTSMK2  433323 non-null  float64
 149  STOPSMK2  433323 non-null  object
 150  MENTCIGS  433323 non-null  object
 151  MENTECIG  433323 non-null  object
 152  HEATTBCO  433323 non-null  object
 153  FIREARM5  433323 non-null  object
 154  GUNLOAD   433323 non-null  object
 155  LOADULK2  433323 non-null  object
 156  HASYMP1   433323 non-null  object
 157  HASYMP2   433323 non-null  object
 158  HASYMP3   433323 non-null  object
 159  HASYMP4   433323 non-null  object
 160  HASYMP5   433323 non-null  object
 161  HASYMP6   433323 non-null  object
 162  STRSYMP1  433323 non-null  object
 163  STRSYMP2  433323 non-null  object
 164  STRSYMP3  433323 non-null  object
 165  STRSYMP4  433323 non-null  object
 166  STRSYMP5  433323 non-null  object
 167  STRSYMP6  433323 non-null  object
 168  FIRSTAID  433323 non-null  float64
 169  ASPIRIN   433323 non-null  float64
 170  BIRTHSEX  433323 non-null  float64
 171  SOMALE    433323 non-null  object
 172  SOFEMALE  433323 non-null  object
 173  TRNSGNDR  433323 non-null  float64
 174  MARIJAN1  433323 non-null  float64
 175  MARJSMOK  433323 non-null  object
 176  MARJEAT   433323 non-null  object
 177  MARJVAPE  433323 non-null  object
 178  MARJDAB   433323 non-null  object
 179  MARJOTHR  433323 non-null  object
 180  USEMRJN4  433323 non-null  object
 181  ACEDEPRS  433323 non-null  object
 182  ACEDRINK  433323 non-null  object
 183  ACEDRUGS  433323 non-null  object
 184  ACEPRISN  433323 non-null  object
 185  ACEDIVRC  433323 non-null  object
 186  ACEPUNCH  433323 non-null  object
 187  ACEHURT1  433323 non-null  object
 188  ACESWEAR  433323 non-null  object
 189  ACEADSAF  433323 non-null  float64
 190  ACEADNED  433323 non-null  float64
 191  IMFVPLA4  433323 non-null  float64
 192  HPVADVC4  433323 non-null  object
 193  HPVADSHT  433323 non-null  float64
 194  TETANUS1  433323 non-null  object
 195  COVIDVA1  433323 non-null  object
 196  COVIDNU2  433323 non-null  float64
 197  LSATISFY  433323 non-null  object
 198  EMTSUPRT  433323 non-null  object
 199  SDLONELY  433323 non-null  object
 200  SDHEMPLY  433323 non-null  object
 201  FOODSTMP  433323 non-null  object
 202  SDHFOOD1  433323 non-null  object
 203  SDHBILLS  433323 non-null  float64
 204  SDHUTILS  433323 non-null  object
 205  SDHTRNSP  433323 non-null  object
 206  SDHSTRE1  433323 non-null  object
 207  RRCLASS3  433323 non-null  float64
 208  RRCOGNT2  433323 non-null  float64
 209  RRTREAT   433323 non-null  float64
 210  RRATWRK2  433323 non-null  float64
 211  RRHCARE4  433323 non-null  float64
 212  RRPHYSM2  433323 non-null  float64
 213  RCSGEND1  433323 non-null  float64
 214  RCSXBRTH  433323 non-null  float64
 215  RCSRLTN2  433323 non-null  float64
 216  CASTHDX2  433323 non-null  object
 217  CASTHNO2  433323 non-null  object
 218  QSTVER    433323 non-null  float64
 219  QSTLANG   433323 non-null  object
 220  _METSTAT  433323 non-null  object
 221  _URBSTAT  433323 non-null  object
 222  MSCODE    433323 non-null  object
 223  _STSTR    433323 non-null  float64
 224  _STRWT    433323 non-null  float64
 225  _RAWRAKE  433323 non-null  float64
 226  _WT2RAKE  433323 non-null  float64
 227  _IMPRACE  433323 non-null  object
 228  _CHISPNC  433323 non-null  object
 229  _CRACE1   433323 non-null  float64
 230  CAGEG     433323 non-null  float64
 231  _CLLCPWT  433323 non-null  float64
 232  _DUALUSE  433323 non-null  object
 233  _DUALCOR  433323 non-null  float64
 234  _LLCPWT2  433323 non-null  float64
 235  _LLCPWT   433323 non-null  float64
 236  _RFHLTH   433323 non-null  object
 237  _PHYS14D  433323 non-null  object
 238  _MENT14D  433323 non-null  object
 239  _HLTHPL1  433323 non-null  object
 240  _HCVU653  433323 non-null  object
 241  _TOTINDA  433323 non-null  object
 242  METVL12_  433323 non-null  float64
 243  METVL22_  433323 non-null  float64
 244  MAXVO21_  433323 non-null  float64
 245  FC601_    433323 non-null  float64
 246  ACTIN13_  433323 non-null  object
 247  ACTIN23_  433323 non-null  object
 248  PADUR1_   433323 non-null  float64
 249  PADUR2_   433323 non-null  float64
 250  PAFREQ1_  433323 non-null  float64
 251  PAFREQ2_  433323 non-null  float64
 252  _MINAC12  433323 non-null  float64
 253  _MINAC22  433323 non-null  float64
 254  STRFREQ_  433323 non-null  float64
 255  PAMISS3_  433323 non-null  float64
 256  PAMIN13_  433323 non-null  float64
 257  PAMIN23_  433323 non-null  float64
 258  PA3MIN_   433323 non-null  float64
 259  PAVIG13_  433323 non-null  float64
 260  PAVIG23_  433323 non-null  float64
 261  PA3VIGM_  433323 non-null  float64
 262  _PACAT3   433323 non-null  object
 263  _PAINDX3  433323 non-null  object
 264  _PA30023  433323 non-null  object
 265  _PASTRNG  433323 non-null  object
 266  _PAREC3   433323 non-null  object
 267  _PASTAE3  433323 non-null  object
 268  _RFHYPE6  433323 non-null  object
 269  _RFCHOL3  433323 non-null  object
 270  _MICHD    433323 non-null  object
 271  _LTASTH1  433323 non-null  object
 272  _CASTHM1  433323 non-null  object
 273  _ASTHMS1  433323 non-null  object
 274  _DRDXAR2  433323 non-null  object
 275  _MRACE1   433323 non-null  float64
 276  _HISPANC  433323 non-null  object
 277  _RACE     433323 non-null  object
 278  _RACEG21  433323 non-null  object
 279  _RACEGR3  433323 non-null  object
 280  _RACEPRV  433323 non-null  object
 281  _SEX      433323 non-null  object
 282  _AGEG5YR  433323 non-null  object
 283  _AGE65YR  433323 non-null  object
 284  _AGE80    433323 non-null  float64
 285  _AGE_G    433323 non-null  object
 286  HTIN4     433323 non-null  float64
 287  HTM4      433323 non-null  float64
 288  WTKG3     433323 non-null  float64
 289  _BMI5     433323 non-null  float64
 290  _BMI5CAT  433323 non-null  object
 291  _RFBMI5   433323 non-null  object
 292  _CHLDCNT  433323 non-null  object
 293  _EDUCAG   433323 non-null  object
 294  _INCOMG1  433323 non-null  object
 295  _SMOKER3  433323 non-null  object
 296  _RFSMOK3  433323 non-null  object
 297  _CURECI2  433323 non-null  object
 298  DRNKANY6  433323 non-null  object
 299  DROCDY4_  433323 non-null  float64
 300  _RFBING6  433323 non-null  object
 301  _DRNKWK2  433323 non-null  float64
 302  _RFDRHV8  433323 non-null  object
 303  _FLSHOT7  433323 non-null  object
 304  _PNEUMO3  433323 non-null  object
 305  _AIDTST4  433323 non-null  object
 306  _RFSEAT2  433323 non-null  object
 307  _RFSEAT3  433323 non-null  object
 308  _DRNKDRV  433323 non-null  object
dtypes: float64(117), object(192)
memory usage: 1021.6+ MB

## Detect and remove outliers

Since this is healthcare data and for any particular disease or health condition the percentage of unhealthy people for that disease is very less so all the target points will be outliers.

So detecting and removing outliers will not be a good decision here.

## Target Analysis

We will take into consideration the critical healthcare diseases.

In [27]:
df['DRNK3GE5'].value_counts()

DRNK3GE5
0.0     380247
1.0      19088
2.0      10724
4.0       4945
3.0       4870
5.0       3382
30.0      1843
10.0      1710
6.0       1338
8.0       1306
15.0       882
20.0       747
7.0        741
12.0       520
25.0       266
14.0       106
16.0        87
28.0        84
9.0         78
29.0        43
23.0        37
24.0        35
18.0        35
26.0        30
22.0        26
13.0        25
21.0        25
27.0        22
76.0        19
17.0        18
11.0        12
19.0         7
31.0         6
50.0         3
55.0         2
32.0         2
48.0         2
40.0         2
69.0         1
52.0         1
45.0         1
64.0         1
36.0         1
60.0         1
73.0         1
39.0         1
Name: count, dtype: int64

In [28]:
def mortality_index(row):
  if( (row['CVDINFR4']=='Yes') or (row['CVDSTRK3']=='Yes') or (row['DIABETE4']=='Yes') or (row['DIABETE4']=='Yes during pregnancy')
      or (row['CHCCOPD3']=='Yes') or (row['CHCKDNY2']=='Yes')
    or (row['BPHIGH6']=='Yes')):

     return 1

  return 0

In [29]:
df['MORTRT1'] = df.apply(mortality_index, axis=1)

/tmp/ipykernel_10339/2627491111.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['MORTRT1'] = df.apply(mortality_index, axis=1)

In [30]:
# for i in df:
#   if (df[i].dtype == 'object'):
#     try:
#         sns.countplot(x = df[i], hue = df['MORTRT1'])
#         plt.show()
#     except:
#         print(f'An exception occured for {i}')

In [31]:
# for i in df:
#   if (df[i].dtype == 'float64'):
#     try:
#         sns.barplot(y = df[i], x = df['MORTRT1'])
#         plt.show()
#     except:
#         print(f'An exception occured for {i}')

In [32]:
df = df.drop(['CVDINFR4', 'CVDSTRK3', 'DIABETE4', 'CHCCOPD3', 'CHCKDNY2', 'BPHIGH6'], axis=1)

We can see that there are trends in the data.

## Deep Analysis

In [33]:
df[num].kurt()

_STATE        -0.718734
NUMADULT      14.030695
LNDSXBRT    3488.823090
CELSXBRT     223.449194
HHADULT       18.263501
PHYSHLTH       3.341585
MENTHLTH       3.575320
POORHLTH       6.527852
PRIMINS1       2.335794
EXRACT12     100.868239
EXEROFT1      19.006510
EXERHMM1      10.407861
EXRACT22      -0.160303
EXEROFT2      19.432358
EXERHMM2      12.661446
STRENGTH      -1.954693
DIABAGE4       6.311316
NUMHHOL4       0.443286
CPDEMO1C      18.748374
CHILDREN     298.517212
WEIGHT2       11.917017
HEIGHT3       22.425988
FALL12MN     430.486412
FALLINJ5    2382.628072
ALCDAY4       -1.885023
AVEDRNK3     163.488081
DRNK3GE5      98.537570
MAXDRNKS      69.018424
FLSHTMY3      15.460044
HIVTSTD3       1.958892
DRNKDRI2    2802.405514
CHKHEMO3    1382.684524
ARTHDIS2      85.891191
JOINPAI2     413.105442
LCSFIRST      84.124261
LCSLAST      102.468870
LCSNUMCG     731.707054
LCSCTWHN     615.495697
HOWLONG     1695.648443
PSATIME1     106.614418
PSASUGS1      75.607204
COLNSIGM     356.512929
COLNTES1     102.198233
SIGMTES1     556.322520
LASTSIG4    5725.379864
VCLNTES2    2557.668832
STOLTEST     459.375265
STOOLDN2     623.754921
CNCRDIFF     234.218279
CNCRAGE       29.462732
CNCRTYP2     113.270686
CSRVDOC1     552.212309
CSRVCTL2    4035.619005
CDWORRY       74.551624
CDHOUS1       48.127009
CDSOCIA1      65.675864
CRGVREL4    1044.094081
CRGVPRB3     444.350723
CRGVEXPT      43.021218
LASTSMK2     338.196051
FIRSTAID      52.698901
ASPIRIN       17.762535
BIRTHSEX      11.619423
TRNSGNDR      -0.834288
MARIJAN1      68.106364
ACEADSAF       3.935758
ACEADNED       3.507030
IMFVPLA4    6789.604594
HPVADSHT     360.410348
COVIDNU2       1.143006
SDHBILLS       3.390697
RRCLASS3     129.596336
RRCOGNT2       5.610728
RRTREAT        7.559733
RRATWRK2      22.441462
RRHCARE4       6.890921
RRPHYSM2      10.234733
RCSGEND1      70.519523
RCSXBRTH     175.122549
RCSRLTN2      63.309896
QSTVER         0.148584
_STSTR        -0.718535
_STRWT        62.193147
_RAWRAKE      19.621888
_WT2RAKE      70.051230
_CRACE1      118.794552
CAGEG         10.851672
_CLLCPWT     669.121820
_DUALCOR      -0.092225
_LLCPWT2      48.054632
_LLCPWT      170.989235
METVL12_      -0.942736
METVL22_      -1.235567
MAXVO21_       0.201665
FC601_         0.201526
PADUR1_       13.244649
PADUR2_       14.958410
PAFREQ1_     209.621492
PAFREQ2_     289.087213
_MINAC12    2213.222078
_MINAC22    3075.081953
STRFREQ_     310.826828
PAMISS3_      95.937244
PAMIN13_    3651.660352
PAMIN23_    2070.139468
PA3MIN_     1416.745421
PAVIG13_    6779.723487
PAVIG23_    3203.803782
PA3VIGM_    2594.370897
_MRACE1       34.369764
_AGE80        -0.469670
HTIN4          8.386180
HTM4          12.208266
WTKG3          1.882098
_BMI5          2.176408
DROCDY4_       9.215698
_DRNKWK2       8.263550
dtype: float64

In [34]:
# for i in num:
#   sns.distplot(df[i])
#   plt.title(f"Distribution of {i}")
#   plt.show()

In [35]:
# for i in num:
#   sns.boxplot(df[i])
#   plt.title(f"Boxplot of {i}")
#   plt.show()

**Due to the inherent diversity of patient health conditions and behavioral profiles within the cohort, significant variance and statistical outliers are observable across all features. Because these anomalies represent true clinical variance rather than systemic noise, removing them would introduce selection bias and degrade the model's capacity to predict high-risk or atypical cases. Consequently, outliers were systematically retained to ensure the final model remains robust and representative of a diverse healthcare population.**

In [36]:
# import time

# for i in cat:
#   try:
#       print(df[i].value_counts(normalize=True) * 100)
#       print('_________________')
#       print()

#       # Pause the execution for 2 seconds
#       time.sleep(2)
#   except:
#       print(f'An exception occured for {i}')
#       time.sleep(2)

Multivariate Analysis

In [37]:
corr_matrix = df.corr(numeric_only=True)
corr_matrix.to_csv("correlation_matrix.csv")

In [38]:
dff = df.copy()

## Encoding

We will one hot encode the important columns

In [39]:
imp_cols = ['BPMEDS1', 'HAVARTH4', 'EMPLOY1', 'DIFFWALK', '_RFHLTH', '_RFHYPE6', '_RFCHOL3', '_MICHD', '_AGE_G']

dff = pd.get_dummies(dff, columns=imp_cols, dtype=int, drop_first=True)

In [40]:
dff.shape

(433323, 330)

Now we will systematically label encode the Yes/No columns

In [41]:
for i in cols3:
  try:
    dff[i] = dff[i].replace({"Yes":1, "No":0, "Don't know / Not sure":7, "Refused":9})
  except:
    print(f"Not found column {i}")

Not found column BPMEDS1
Not found column CVDINFR4
Not found column CVDINFR4
Not found column CVDSTRK3
Not found column CHCCOPD3
Not found column CHCKDNY2
Not found column HAVARTH4
Not found column DIFFWALK

/tmp/ipykernel_10339/678836765.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dff[i] = dff[i].replace({"Yes":1, "No":0, "Don't know / Not sure":7, "Refused":9})

In [42]:
for i in cols4:
  try:
    dff[i] = dff[i].replace({"Yes":1, "No":0, "Don't know / Not sure":7, "Refused":9})
  except:
    print(f"Not found column {i}")

Not found column _RFHYPE6
Not found column _RFCHOL3

/tmp/ipykernel_10339/1780832109.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dff[i] = dff[i].replace({"Yes":1, "No":0, "Don't know / Not sure":7, "Refused":9})

In [43]:
dff.info(max_cols=500)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 330 columns):
 #    Column                         Non-Null Count   Dtype
---   ------                         --------------   -----
 0    _STATE                         433323 non-null  float64
 1    DISPCODE                       433323 non-null  object
 2    STATERE1                       433323 non-null  object
 3    LADULT1                        433323 non-null  object
 4    NUMADULT                       433323 non-null  float64
 5    LNDSXBRT                       433323 non-null  float64
 6    SAFETIME                       433323 non-null  object
 7    CADULT1                        433323 non-null  object
 8    CELSXBRT                       433323 non-null  float64
 9    CSTATE1                        433323 non-null  object
 10   HHADULT                        433323 non-null  float64
 11   SEXVAR                         433323 non-null  object
 12   GENHLTH                        433323 non-null  object
 13   PHYSHLTH                       433323 non-null  float64
 14   MENTHLTH                       433323 non-null  float64
 15   POORHLTH                       433323 non-null  float64
 16   PRIMINS1                       433323 non-null  float64
 17   PERSDOC3                       433323 non-null  object
 18   MEDCOST1                       433323 non-null  object
 19   CHECKUP1                       433323 non-null  object
 20   EXERANY2                       433323 non-null  object
 21   EXRACT12                       433323 non-null  float64
 22   EXEROFT1                       433323 non-null  float64
 23   EXERHMM1                       433323 non-null  float64
 24   EXRACT22                       433323 non-null  float64
 25   EXEROFT2                       433323 non-null  float64
 26   EXERHMM2                       433323 non-null  float64
 27   STRENGTH                       433323 non-null  float64
 28   CHOLCHK3                       433323 non-null  object
 29   TOLDHI3                        433323 non-null  object
 30   CHOLMED3                       433323 non-null  object
 31   CVDCRHD4                       433323 non-null  object
 32   ASTHMA3                        433323 non-null  object
 33   ASTHNOW                        433323 non-null  object
 34   CHCSCNC1                       433323 non-null  object
 35   CHCOCNC1                       433323 non-null  object
 36   ADDEPEV3                       433323 non-null  object
 37   DIABAGE4                       433323 non-null  float64
 38   MARITAL                        433323 non-null  object
 39   EDUCA                          433323 non-null  object
 40   RENTHOM1                       433323 non-null  object
 41   NUMHHOL4                       433323 non-null  float64
 42   CPDEMO1C                       433323 non-null  float64
 43   VETERAN3                       433323 non-null  object
 44   CHILDREN                       433323 non-null  float64
 45   INCOME3                        433323 non-null  object
 46   PREGNANT                       433323 non-null  object
 47   WEIGHT2                        433323 non-null  float64
 48   HEIGHT3                        433323 non-null  float64
 49   DEAF                           433323 non-null  object
 50   BLIND                          433323 non-null  object
 51   DECIDE                         433323 non-null  object
 52   DIFFDRES                       433323 non-null  object
 53   DIFFALON                       433323 non-null  object
 54   FALL12MN                       433323 non-null  float64
 55   FALLINJ5                       433323 non-null  float64
 56   SMOKE100                       433323 non-null  object
 57   SMOKDAY2                       433323 non-null  object
 58   USENOW3                        433323 non-null  object
 59   ECIGNOW2                       433323 non-null  object
 60   ALCDAY4                        433323 non-null  float64
 61   AVEDRNK3                       433323 non-null  float64
 62   DRNK3GE5                       433323 non-null  float64
 63   MAXDRNKS                       433323 non-null  float64
 64   FLUSHOT7                       433323 non-null  object
 65   FLSHTMY3                       433323 non-null  float64
 66   PNEUVAC4                       433323 non-null  object
 67   SHINGLE2                       433323 non-null  object
 68   HIVTST7                        433323 non-null  object
 69   HIVTSTD3                       433323 non-null  float64
 70   SEATBELT                       433323 non-null  object
 71   DRNKDRI2                       433323 non-null  float64
 72   COVIDPO1                       433323 non-null  object
 73   COVIDSM1                       433323 non-null  object
 74   COVIDACT                       433323 non-null  object
 75   DIABTYPE                       433323 non-null  object
 76   INSULIN1                       433323 non-null  object
 77   CHKHEMO3                       433323 non-null  float64
 78   EYEEXAM1                       433323 non-null  object
 79   FEETSORE                       433323 non-null  object
 80   ARTHEXER                       433323 non-null  object
 81   ARTHEDU                        433323 non-null  object
 82   LMTJOIN3                       433323 non-null  object
 83   ARTHDIS2                       433323 non-null  float64
 84   JOINPAI2                       433323 non-null  float64
 85   LCSFIRST                       433323 non-null  float64
 86   LCSLAST                        433323 non-null  float64
 87   LCSNUMCG                       433323 non-null  float64
 88   LCSCTSC1                       433323 non-null  object
 89   LCSSCNCR                       433323 non-null  object
 90   LCSCTWHN                       433323 non-null  float64
 91   HADMAM                         433323 non-null  object
 92   HOWLONG                        433323 non-null  float64
 93   CERVSCRN                       433323 non-null  object
 94   CRVCLPAP                       433323 non-null  object
 95   CRVCLHPV                       433323 non-null  object
 96   HADHYST2                       433323 non-null  object
 97   PSATEST1                       433323 non-null  object
 98   PSATIME1                       433323 non-null  float64
 99   PSASUGS1                       433323 non-null  float64
 100  HADSIGM4                       433323 non-null  object
 101  COLNSIGM                       433323 non-null  float64
 102  COLNTES1                       433323 non-null  float64
 103  SIGMTES1                       433323 non-null  float64
 104  LASTSIG4                       433323 non-null  float64
 105  COLNCNCR                       433323 non-null  object
 106  VIRCOLO1                       433323 non-null  object
 107  VCLNTES2                       433323 non-null  float64
 108  SMALSTOL                       433323 non-null  object
 109  STOLTEST                       433323 non-null  float64
 110  STOOLDN2                       433323 non-null  float64
 111  BLDSTFIT                       433323 non-null  object
 112  CNCRDIFF                       433323 non-null  float64
 113  CNCRAGE                        433323 non-null  float64
 114  CNCRTYP2                       433323 non-null  float64
 115  CSRVDOC1                       433323 non-null  float64
 116  CSRVSUM                        433323 non-null  object
 117  CSRVRTRN                       433323 non-null  object
 118  CSRVINST                       433323 non-null  object
 119  CSRVINSR                       433323 non-null  object
 120  CSRVDEIN                       433323 non-null  object
 121  CSRVCLIN                       433323 non-null  object
 122  CSRVPAIN                       433323 non-null  object
 123  CSRVCTL2                       433323 non-null  float64
 124  CIMEMLO1                       433323 non-null  object
 125  CDWORRY                        433323 non-null  float64
 126  CDDISCU1                       433323 non-null  object
 127  CDHOUS1                        433323 non-null  float64
 128  CDSOCIA1                       433323 non-null  float64
 129  CAREGIV1                       433323 non-null  object
 130  CRGVREL4                       433323 non-null  float64
 131  CRGVLNG1                       433323 non-null  object
 132  CRGVHRS1                       433323 non-null  object
 133  CRGVPRB3                       433323 non-null  float64
 134  CRGVALZD                       433323 non-null  object
 135  CRGVPER1                       433323 non-null  object
 136  CRGVHOU1                       433323 non-null  object
 137  CRGVEXPT                       433323 non-null  float64
 138  LASTSMK2                       433323 non-null  float64
 139  STOPSMK2                       433323 non-null  object
 140  MENTCIGS                       433323 non-null  object
 141  MENTECIG                       433323 non-null  object
 142  HEATTBCO                       433323 non-null  object
 143  FIREARM5                       433323 non-null  object
 144  GUNLOAD                        433323 non-null  object
 145  LOADULK2                       433323 non-null  object
 146  HASYMP1                        433323 non-null  object
 147  HASYMP2                        433323 non-null  object
 148  HASYMP3                        433323 non-null  object
 149  HASYMP4                        433323 non-null  object
 150  HASYMP5                        433323 non-null  object
 151  HASYMP6                        433323 non-null  object
 152  STRSYMP1                       433323 non-null  object
 153  STRSYMP2                       433323 non-null  object
 154  STRSYMP3                       433323 non-null  object
 155  STRSYMP4                       433323 non-null  object
 156  STRSYMP5                       433323 non-null  object
 157  STRSYMP6                       433323 non-null  object
 158  FIRSTAID                       433323 non-null  float64
 159  ASPIRIN                        433323 non-null  float64
 160  BIRTHSEX                       433323 non-null  float64
 161  SOMALE                         433323 non-null  object
 162  SOFEMALE                       433323 non-null  object
 163  TRNSGNDR                       433323 non-null  float64
 164  MARIJAN1                       433323 non-null  float64
 165  MARJSMOK                       433323 non-null  object
 166  MARJEAT                        433323 non-null  object
 167  MARJVAPE                       433323 non-null  object
 168  MARJDAB                        433323 non-null  object
 169  MARJOTHR                       433323 non-null  object
 170  USEMRJN4                       433323 non-null  object
 171  ACEDEPRS                       433323 non-null  object
 172  ACEDRINK                       433323 non-null  object
 173  ACEDRUGS                       433323 non-null  object
 174  ACEPRISN                       433323 non-null  object
 175  ACEDIVRC                       433323 non-null  object
 176  ACEPUNCH                       433323 non-null  object
 177  ACEHURT1                       433323 non-null  object
 178  ACESWEAR                       433323 non-null  object
 179  ACEADSAF                       433323 non-null  float64
 180  ACEADNED                       433323 non-null  float64
 181  IMFVPLA4                       433323 non-null  float64
 182  HPVADVC4                       433323 non-null  object
 183  HPVADSHT                       433323 non-null  float64
 184  TETANUS1                       433323 non-null  object
 185  COVIDVA1                       433323 non-null  object
 186  COVIDNU2                       433323 non-null  float64
 187  LSATISFY                       433323 non-null  object
 188  EMTSUPRT                       433323 non-null  object
 189  SDLONELY                       433323 non-null  object
 190  SDHEMPLY                       433323 non-null  object
 191  FOODSTMP                       433323 non-null  object
 192  SDHFOOD1                       433323 non-null  object
 193  SDHBILLS                       433323 non-null  float64
 194  SDHUTILS                       433323 non-null  object
 195  SDHTRNSP                       433323 non-null  object
 196  SDHSTRE1                       433323 non-null  object
 197  RRCLASS3                       433323 non-null  float64
 198  RRCOGNT2                       433323 non-null  float64
 199  RRTREAT                        433323 non-null  float64
 200  RRATWRK2                       433323 non-null  float64
 201  RRHCARE4                       433323 non-null  float64
 202  RRPHYSM2                       433323 non-null  float64
 203  RCSGEND1                       433323 non-null  float64
 204  RCSXBRTH                       433323 non-null  float64
 205  RCSRLTN2                       433323 non-null  float64
 206  CASTHDX2                       433323 non-null  object
 207  CASTHNO2                       433323 non-null  object
 208  QSTVER                         433323 non-null  float64
 209  QSTLANG                        433323 non-null  object
 210  _METSTAT                       433323 non-null  object
 211  _URBSTAT                       433323 non-null  object
 212  MSCODE                         433323 non-null  object
 213  _STSTR                         433323 non-null  float64
 214  _STRWT                         433323 non-null  float64
 215  _RAWRAKE                       433323 non-null  float64
 216  _WT2RAKE                       433323 non-null  float64
 217  _IMPRACE                       433323 non-null  object
 218  _CHISPNC                       433323 non-null  object
 219  _CRACE1                        433323 non-null  float64
 220  CAGEG                          433323 non-null  float64
 221  _CLLCPWT                       433323 non-null  float64
 222  _DUALUSE                       433323 non-null  int64
 223  _DUALCOR                       433323 non-null  float64
 224  _LLCPWT2                       433323 non-null  float64
 225  _LLCPWT                        433323 non-null  float64
 226  _PHYS14D                       433323 non-null  object
 227  _MENT14D                       433323 non-null  object
 228  _HLTHPL1                       433323 non-null  int64
 229  _HCVU653                       433323 non-null  int64
 230  _TOTINDA                       433323 non-null  object
 231  METVL12_                       433323 non-null  float64
 232  METVL22_                       433323 non-null  float64
 233  MAXVO21_                       433323 non-null  float64
 234  FC601_                         433323 non-null  float64
 235  ACTIN13_                       433323 non-null  object
 236  ACTIN23_                       433323 non-null  object
 237  PADUR1_                        433323 non-null  float64
 238  PADUR2_                        433323 non-null  float64
 239  PAFREQ1_                       433323 non-null  float64
 240  PAFREQ2_                       433323 non-null  float64
 241  _MINAC12                       433323 non-null  float64
 242  _MINAC22                       433323 non-null  float64
 243  STRFREQ_                       433323 non-null  float64
 244  PAMISS3_                       433323 non-null  float64
 245  PAMIN13_                       433323 non-null  float64
 246  PAMIN23_                       433323 non-null  float64
 247  PA3MIN_                        433323 non-null  float64
 248  PAVIG13_                       433323 non-null  float64
 249  PAVIG23_                       433323 non-null  float64
 250  PA3VIGM_                       433323 non-null  float64
 251  _PACAT3                        433323 non-null  object
 252  _PAINDX3                       433323 non-null  object
 253  _PA30023                       433323 non-null  object
 254  _PASTRNG                       433323 non-null  object
 255  _PAREC3                        433323 non-null  object
 256  _PASTAE3                       433323 non-null  int64
 257  _LTASTH1                       433323 non-null  int64
 258  _CASTHM1                       433323 non-null  object
 259  _ASTHMS1                       433323 non-null  object
 260  _DRDXAR2                       433323 non-null  object
 261  _MRACE1                        433323 non-null  float64
 262  _HISPANC                       433323 non-null  int64
 263  _RACE                          433323 non-null  object
 264  _RACEG21                       433323 non-null  object
 265  _RACEGR3                       433323 non-null  object
 266  _RACEPRV                       433323 non-null  object
 267  _SEX                           433323 non-null  object
 268  _AGEG5YR                       433323 non-null  object
 269  _AGE65YR                       433323 non-null  object
 270  _AGE80                         433323 non-null  float64
 271  HTIN4                          433323 non-null  float64
 272  HTM4                           433323 non-null  float64
 273  WTKG3                          433323 non-null  float64
 274  _BMI5                          433323 non-null  float64
 275  _BMI5CAT                       433323 non-null  object
 276  _RFBMI5                        433323 non-null  int64
 277  _CHLDCNT                       433323 non-null  object
 278  _EDUCAG                        433323 non-null  object
 279  _INCOMG1                       433323 non-null  object
 280  _SMOKER3                       433323 non-null  object
 281  _RFSMOK3                       433323 non-null  int64
 282  _CURECI2                       433323 non-null  object
 283  DRNKANY6                       433323 non-null  int64
 284  DROCDY4_                       433323 non-null  float64
 285  _RFBING6                       433323 non-null  int64
 286  _DRNKWK2                       433323 non-null  float64
 287  _RFDRHV8                       433323 non-null  int64
 288  _FLSHOT7                       433323 non-null  object
 289  _PNEUMO3                       433323 non-null  object
 290  _AIDTST4                       433323 non-null  object
 291  _RFSEAT2                       433323 non-null  object
 292  _RFSEAT3                       433323 non-null  object
 293  _DRNKDRV                       433323 non-null  int64
 294  MORTRT1                        433323 non-null  int64
 295  BPMEDS1_No                     433323 non-null  int64
 296  BPMEDS1_Not asked or missing   433323 non-null  int64
 297  BPMEDS1_Refused                433323 non-null  int64
 298  BPMEDS1_Yes                    433323 non-null  int64
 299  HAVARTH4_No                    433323 non-null  int64
 300  HAVARTH4_Not asked or missing  433323 non-null  int64
 301  HAVARTH4_Refused               433323 non-null  int64
 302  HAVARTH4_Yes                   433323 non-null  int64
 303  EMPLOY1_Homemaker              433323 non-null  int64
 304  EMPLOY1_Not asked or missing   433323 non-null  int64
 305  EMPLOY1_Out of work 1+ year    433323 non-null  int64
 306  EMPLOY1_Out of work <1 year    433323 non-null  int64
 307  EMPLOY1_Refused                433323 non-null  int64
 308  EMPLOY1_Retired                433323 non-null  int64
 309  EMPLOY1_Self-employed          433323 non-null  int64
 310  EMPLOY1_Student                433323 non-null  int64
 311  EMPLOY1_unable to work         433323 non-null  int64
 312  DIFFWALK_No                    433323 non-null  int64
 313  DIFFWALK_Not asked or missing  433323 non-null  int64
 314  DIFFWALK_Refused               433323 non-null  int64
 315  DIFFWALK_Yes                   433323 non-null  int64
 316  _RFHLTH_Fair or Poor           433323 non-null  int64
 317  _RFHLTH_Good or Better         433323 non-null  int64
 318  _RFHYPE6_Refused               433323 non-null  int64
 319  _RFHYPE6_Yes                   433323 non-null  int64
 320  _RFCHOL3_Not asked or missing  433323 non-null  int64
 321  _RFCHOL3_Refused               433323 non-null  int64

Now we will label encode the remaining columns

In [44]:
cat = dff.select_dtypes(include='object').columns.tolist()
L = LabelEncoder()
for i in cat:
  dff[i] = dff[i].astype(str)
  dff[i] = L.fit_transform(dff[i])

In [45]:
dff.info(max_cols=500)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 330 columns):
 #    Column                         Non-Null Count   Dtype
---   ------                         --------------   -----
 0    _STATE                         433323 non-null  float64
 1    DISPCODE                       433323 non-null  int64
 2    STATERE1                       433323 non-null  int64
 3    LADULT1                        433323 non-null  int64
 4    NUMADULT                       433323 non-null  float64
 5    LNDSXBRT                       433323 non-null  float64
 6    SAFETIME                       433323 non-null  int64
 7    CADULT1                        433323 non-null  int64
 8    CELSXBRT                       433323 non-null  float64
 9    CSTATE1                        433323 non-null  int64
 10   HHADULT                        433323 non-null  float64
 11   SEXVAR                         433323 non-null  int64
 12   GENHLTH                        433323 non-null  int64
 13   PHYSHLTH                       433323 non-null  float64
 14   MENTHLTH                       433323 non-null  float64
 15   POORHLTH                       433323 non-null  float64
 16   PRIMINS1                       433323 non-null  float64
 17   PERSDOC3                       433323 non-null  int64
 18   MEDCOST1                       433323 non-null  int64
 19   CHECKUP1                       433323 non-null  int64
 20   EXERANY2                       433323 non-null  int64
 21   EXRACT12                       433323 non-null  float64
 22   EXEROFT1                       433323 non-null  float64
 23   EXERHMM1                       433323 non-null  float64
 24   EXRACT22                       433323 non-null  float64
 25   EXEROFT2                       433323 non-null  float64
 26   EXERHMM2                       433323 non-null  float64
 27   STRENGTH                       433323 non-null  float64
 28   CHOLCHK3                       433323 non-null  int64
 29   TOLDHI3                        433323 non-null  int64
 30   CHOLMED3                       433323 non-null  int64
 31   CVDCRHD4                       433323 non-null  int64
 32   ASTHMA3                        433323 non-null  int64
 33   ASTHNOW                        433323 non-null  int64
 34   CHCSCNC1                       433323 non-null  int64
 35   CHCOCNC1                       433323 non-null  int64
 36   ADDEPEV3                       433323 non-null  int64
 37   DIABAGE4                       433323 non-null  float64
 38   MARITAL                        433323 non-null  int64
 39   EDUCA                          433323 non-null  int64
 40   RENTHOM1                       433323 non-null  int64
 41   NUMHHOL4                       433323 non-null  float64
 42   CPDEMO1C                       433323 non-null  float64
 43   VETERAN3                       433323 non-null  int64
 44   CHILDREN                       433323 non-null  float64
 45   INCOME3                        433323 non-null  int64
 46   PREGNANT                       433323 non-null  int64
 47   WEIGHT2                        433323 non-null  float64
 48   HEIGHT3                        433323 non-null  float64
 49   DEAF                           433323 non-null  int64
 50   BLIND                          433323 non-null  int64
 51   DECIDE                         433323 non-null  int64
 52   DIFFDRES                       433323 non-null  int64
 53   DIFFALON                       433323 non-null  int64
 54   FALL12MN                       433323 non-null  float64
 55   FALLINJ5                       433323 non-null  float64
 56   SMOKE100                       433323 non-null  int64
 57   SMOKDAY2                       433323 non-null  int64
 58   USENOW3                        433323 non-null  int64
 59   ECIGNOW2                       433323 non-null  int64
 60   ALCDAY4                        433323 non-null  float64
 61   AVEDRNK3                       433323 non-null  float64
 62   DRNK3GE5                       433323 non-null  float64
 63   MAXDRNKS                       433323 non-null  float64
 64   FLUSHOT7                       433323 non-null  int64
 65   FLSHTMY3                       433323 non-null  float64
 66   PNEUVAC4                       433323 non-null  int64
 67   SHINGLE2                       433323 non-null  int64
 68   HIVTST7                        433323 non-null  int64
 69   HIVTSTD3                       433323 non-null  float64
 70   SEATBELT                       433323 non-null  int64
 71   DRNKDRI2                       433323 non-null  float64
 72   COVIDPO1                       433323 non-null  int64
 73   COVIDSM1                       433323 non-null  int64
 74   COVIDACT                       433323 non-null  int64
 75   DIABTYPE                       433323 non-null  int64
 76   INSULIN1                       433323 non-null  int64
 77   CHKHEMO3                       433323 non-null  float64
 78   EYEEXAM1                       433323 non-null  int64
 79   FEETSORE                       433323 non-null  int64
 80   ARTHEXER                       433323 non-null  int64
 81   ARTHEDU                        433323 non-null  int64
 82   LMTJOIN3                       433323 non-null  int64
 83   ARTHDIS2                       433323 non-null  float64
 84   JOINPAI2                       433323 non-null  float64
 85   LCSFIRST                       433323 non-null  float64
 86   LCSLAST                        433323 non-null  float64
 87   LCSNUMCG                       433323 non-null  float64
 88   LCSCTSC1                       433323 non-null  int64
 89   LCSSCNCR                       433323 non-null  int64
 90   LCSCTWHN                       433323 non-null  float64
 91   HADMAM                         433323 non-null  int64
 92   HOWLONG                        433323 non-null  float64
 93   CERVSCRN                       433323 non-null  int64
 94   CRVCLPAP                       433323 non-null  int64
 95   CRVCLHPV                       433323 non-null  int64
 96   HADHYST2                       433323 non-null  int64
 97   PSATEST1                       433323 non-null  int64
 98   PSATIME1                       433323 non-null  float64
 99   PSASUGS1                       433323 non-null  float64
 100  HADSIGM4                       433323 non-null  int64
 101  COLNSIGM                       433323 non-null  float64
 102  COLNTES1                       433323 non-null  float64
 103  SIGMTES1                       433323 non-null  float64
 104  LASTSIG4                       433323 non-null  float64
 105  COLNCNCR                       433323 non-null  int64
 106  VIRCOLO1                       433323 non-null  int64
 107  VCLNTES2                       433323 non-null  float64
 108  SMALSTOL                       433323 non-null  int64
 109  STOLTEST                       433323 non-null  float64
 110  STOOLDN2                       433323 non-null  float64
 111  BLDSTFIT                       433323 non-null  int64
 112  CNCRDIFF                       433323 non-null  float64
 113  CNCRAGE                        433323 non-null  float64
 114  CNCRTYP2                       433323 non-null  float64
 115  CSRVDOC1                       433323 non-null  float64
 116  CSRVSUM                        433323 non-null  int64
 117  CSRVRTRN                       433323 non-null  int64
 118  CSRVINST                       433323 non-null  int64
 119  CSRVINSR                       433323 non-null  int64
 120  CSRVDEIN                       433323 non-null  int64
 121  CSRVCLIN                       433323 non-null  int64
 122  CSRVPAIN                       433323 non-null  int64
 123  CSRVCTL2                       433323 non-null  float64
 124  CIMEMLO1                       433323 non-null  int64
 125  CDWORRY                        433323 non-null  float64
 126  CDDISCU1                       433323 non-null  int64
 127  CDHOUS1                        433323 non-null  float64
 128  CDSOCIA1                       433323 non-null  float64
 129  CAREGIV1                       433323 non-null  int64
 130  CRGVREL4                       433323 non-null  float64
 131  CRGVLNG1                       433323 non-null  int64
 132  CRGVHRS1                       433323 non-null  int64
 133  CRGVPRB3                       433323 non-null  float64
 134  CRGVALZD                       433323 non-null  int64
 135  CRGVPER1                       433323 non-null  int64
 136  CRGVHOU1                       433323 non-null  int64
 137  CRGVEXPT                       433323 non-null  float64
 138  LASTSMK2                       433323 non-null  float64
 139  STOPSMK2                       433323 non-null  int64
 140  MENTCIGS                       433323 non-null  int64
 141  MENTECIG                       433323 non-null  int64
 142  HEATTBCO                       433323 non-null  int64
 143  FIREARM5                       433323 non-null  int64
 144  GUNLOAD                        433323 non-null  int64
 145  LOADULK2                       433323 non-null  int64
 146  HASYMP1                        433323 non-null  int64
 147  HASYMP2                        433323 non-null  int64
 148  HASYMP3                        433323 non-null  int64
 149  HASYMP4                        433323 non-null  int64
 150  HASYMP5                        433323 non-null  int64
 151  HASYMP6                        433323 non-null  int64
 152  STRSYMP1                       433323 non-null  int64
 153  STRSYMP2                       433323 non-null  int64
 154  STRSYMP3                       433323 non-null  int64
 155  STRSYMP4                       433323 non-null  int64
 156  STRSYMP5                       433323 non-null  int64
 157  STRSYMP6                       433323 non-null  int64
 158  FIRSTAID                       433323 non-null  float64
 159  ASPIRIN                        433323 non-null  float64
 160  BIRTHSEX                       433323 non-null  float64
 161  SOMALE                         433323 non-null  int64
 162  SOFEMALE                       433323 non-null  int64
 163  TRNSGNDR                       433323 non-null  float64
 164  MARIJAN1                       433323 non-null  float64
 165  MARJSMOK                       433323 non-null  int64
 166  MARJEAT                        433323 non-null  int64
 167  MARJVAPE                       433323 non-null  int64
 168  MARJDAB                        433323 non-null  int64
 169  MARJOTHR                       433323 non-null  int64
 170  USEMRJN4                       433323 non-null  int64
 171  ACEDEPRS                       433323 non-null  int64
 172  ACEDRINK                       433323 non-null  int64
 173  ACEDRUGS                       433323 non-null  int64
 174  ACEPRISN                       433323 non-null  int64
 175  ACEDIVRC                       433323 non-null  int64
 176  ACEPUNCH                       433323 non-null  int64
 177  ACEHURT1                       433323 non-null  int64
 178  ACESWEAR                       433323 non-null  int64
 179  ACEADSAF                       433323 non-null  float64
 180  ACEADNED                       433323 non-null  float64
 181  IMFVPLA4                       433323 non-null  float64
 182  HPVADVC4                       433323 non-null  int64
 183  HPVADSHT                       433323 non-null  float64
 184  TETANUS1                       433323 non-null  int64
 185  COVIDVA1                       433323 non-null  int64
 186  COVIDNU2                       433323 non-null  float64
 187  LSATISFY                       433323 non-null  int64
 188  EMTSUPRT                       433323 non-null  int64
 189  SDLONELY                       433323 non-null  int64
 190  SDHEMPLY                       433323 non-null  int64
 191  FOODSTMP                       433323 non-null  int64
 192  SDHFOOD1                       433323 non-null  int64
 193  SDHBILLS                       433323 non-null  float64
 194  SDHUTILS                       433323 non-null  int64
 195  SDHTRNSP                       433323 non-null  int64
 196  SDHSTRE1                       433323 non-null  int64
 197  RRCLASS3                       433323 non-null  float64
 198  RRCOGNT2                       433323 non-null  float64
 199  RRTREAT                        433323 non-null  float64
 200  RRATWRK2                       433323 non-null  float64
 201  RRHCARE4                       433323 non-null  float64
 202  RRPHYSM2                       433323 non-null  float64
 203  RCSGEND1                       433323 non-null  float64
 204  RCSXBRTH                       433323 non-null  float64
 205  RCSRLTN2                       433323 non-null  float64
 206  CASTHDX2                       433323 non-null  int64
 207  CASTHNO2                       433323 non-null  int64
 208  QSTVER                         433323 non-null  float64
 209  QSTLANG                        433323 non-null  int64
 210  _METSTAT                       433323 non-null  int64
 211  _URBSTAT                       433323 non-null  int64
 212  MSCODE                         433323 non-null  int64
 213  _STSTR                         433323 non-null  float64
 214  _STRWT                         433323 non-null  float64
 215  _RAWRAKE                       433323 non-null  float64
 216  _WT2RAKE                       433323 non-null  float64
 217  _IMPRACE                       433323 non-null  int64
 218  _CHISPNC                       433323 non-null  int64
 219  _CRACE1                        433323 non-null  float64
 220  CAGEG                          433323 non-null  float64
 221  _CLLCPWT                       433323 non-null  float64
 222  _DUALUSE                       433323 non-null  int64
 223  _DUALCOR                       433323 non-null  float64
 224  _LLCPWT2                       433323 non-null  float64
 225  _LLCPWT                        433323 non-null  float64
 226  _PHYS14D                       433323 non-null  int64
 227  _MENT14D                       433323 non-null  int64
 228  _HLTHPL1                       433323 non-null  int64
 229  _HCVU653                       433323 non-null  int64
 230  _TOTINDA                       433323 non-null  int64
 231  METVL12_                       433323 non-null  float64
 232  METVL22_                       433323 non-null  float64
 233  MAXVO21_                       433323 non-null  float64
 234  FC601_                         433323 non-null  float64
 235  ACTIN13_                       433323 non-null  int64
 236  ACTIN23_                       433323 non-null  int64
 237  PADUR1_                        433323 non-null  float64
 238  PADUR2_                        433323 non-null  float64
 239  PAFREQ1_                       433323 non-null  float64
 240  PAFREQ2_                       433323 non-null  float64
 241  _MINAC12                       433323 non-null  float64
 242  _MINAC22                       433323 non-null  float64
 243  STRFREQ_                       433323 non-null  float64
 244  PAMISS3_                       433323 non-null  float64
 245  PAMIN13_                       433323 non-null  float64
 246  PAMIN23_                       433323 non-null  float64
 247  PA3MIN_                        433323 non-null  float64
 248  PAVIG13_                       433323 non-null  float64
 249  PAVIG23_                       433323 non-null  float64
 250  PA3VIGM_                       433323 non-null  float64
 251  _PACAT3                        433323 non-null  int64
 252  _PAINDX3                       433323 non-null  int64
 253  _PA30023                       433323 non-null  int64
 254  _PASTRNG                       433323 non-null  int64
 255  _PAREC3                        433323 non-null  int64
 256  _PASTAE3                       433323 non-null  int64
 257  _LTASTH1                       433323 non-null  int64
 258  _CASTHM1                       433323 non-null  int64
 259  _ASTHMS1                       433323 non-null  int64
 260  _DRDXAR2                       433323 non-null  int64
 261  _MRACE1                        433323 non-null  float64
 262  _HISPANC                       433323 non-null  int64
 263  _RACE                          433323 non-null  int64
 264  _RACEG21                       433323 non-null  int64
 265  _RACEGR3                       433323 non-null  int64
 266  _RACEPRV                       433323 non-null  int64
 267  _SEX                           433323 non-null  int64
 268  _AGEG5YR                       433323 non-null  int64
 269  _AGE65YR                       433323 non-null  int64
 270  _AGE80                         433323 non-null  float64
 271  HTIN4                          433323 non-null  float64
 272  HTM4                           433323 non-null  float64
 273  WTKG3                          433323 non-null  float64
 274  _BMI5                          433323 non-null  float64
 275  _BMI5CAT                       433323 non-null  int64
 276  _RFBMI5                        433323 non-null  int64
 277  _CHLDCNT                       433323 non-null  int64
 278  _EDUCAG                        433323 non-null  int64
 279  _INCOMG1                       433323 non-null  int64
 280  _SMOKER3                       433323 non-null  int64
 281  _RFSMOK3                       433323 non-null  int64
 282  _CURECI2                       433323 non-null  int64
 283  DRNKANY6                       433323 non-null  int64
 284  DROCDY4_                       433323 non-null  float64
 285  _RFBING6                       433323 non-null  int64
 286  _DRNKWK2                       433323 non-null  float64
 287  _RFDRHV8                       433323 non-null  int64
 288  _FLSHOT7                       433323 non-null  int64
 289  _PNEUMO3                       433323 non-null  int64
 290  _AIDTST4                       433323 non-null  int64
 291  _RFSEAT2                       433323 non-null  int64
 292  _RFSEAT3                       433323 non-null  int64
 293  _DRNKDRV                       433323 non-null  int64
 294  MORTRT1                        433323 non-null  int64
 295  BPMEDS1_No                     433323 non-null  int64
 296  BPMEDS1_Not asked or missing   433323 non-null  int64
 297  BPMEDS1_Refused                433323 non-null  int64
 298  BPMEDS1_Yes                    433323 non-null  int64
 299  HAVARTH4_No                    433323 non-null  int64
 300  HAVARTH4_Not asked or missing  433323 non-null  int64
 301  HAVARTH4_Refused               433323 non-null  int64
 302  HAVARTH4_Yes                   433323 non-null  int64
 303  EMPLOY1_Homemaker              433323 non-null  int64
 304  EMPLOY1_Not asked or missing   433323 non-null  int64
 305  EMPLOY1_Out of work 1+ year    433323 non-null  int64
 306  EMPLOY1_Out of work <1 year    433323 non-null  int64
 307  EMPLOY1_Refused                433323 non-null  int64
 308  EMPLOY1_Retired                433323 non-null  int64
 309  EMPLOY1_Self-employed          433323 non-null  int64
 310  EMPLOY1_Student                433323 non-null  int64
 311  EMPLOY1_unable to work         433323 non-null  int64
 312  DIFFWALK_No                    433323 non-null  int64
 313  DIFFWALK_Not asked or missing  433323 non-null  int64
 314  DIFFWALK_Refused               433323 non-null  int64
 315  DIFFWALK_Yes                   433323 non-null  int64
 316  _RFHLTH_Fair or Poor           433323 non-null  int64
 317  _RFHLTH_Good or Better         433323 non-null  int64
 318  _RFHYPE6_Refused               433323 non-null  int64
 319  _RFHYPE6_Yes                   433323 non-null  int64
 320  _RFCHOL3_Not asked or missing  433323 non-null  int64
 321  _RFCHOL3_Refused               433323 non-null  int64
 322  _RFCHOL3_Yes                   433323 non-null  int64
 323  _MICHD_Not asked or missing    433323 non-null  int64
 324  _MICHD_Reported                433323 non-null  int64

## Train Test Split

In [64]:
from sklearn.model_selection import train_test_split, GridSearchCV
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
import xgboost as xgb
import pickle

In [47]:
X = dff.drop("MORTRT1", axis=1)
Y = dff["MORTRT1"]
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, stratify=Y)

In [48]:
# xtrain_const = sm.add_constant(xtrain)
# model = sm.Logit(ytrain, xtrain_const).fit(method='bfgs')
# print(model.summary())

In [49]:
dff['MORTRT1'].value_counts(normalize=True) * 100

MORTRT1
0    50.292507
1    49.707493
Name: proportion, dtype: float64

Therefore there is no class imbalance

In [50]:
# Feature scaling
# scaler = StandardScaler()
# xtrain_scaled = scaler.fit_transform(xtrain)
# xtest_scaled = scaler.transform(xtest)

In [51]:
dummy = DummyClassifier(strategy = "most_frequent")
dummy.fit(xtrain, ytrain)
print(dummy.score(xtest, ytest))

0.5029250562510817

In [52]:
# Training Classification models
model = LogisticRegression( random_state=42, max_iter=100)
model.fit(xtrain, ytrain)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [53]:
y_pred = model.predict(xtest)
y_proba = model.predict_proba(xtest)[:, 1]

print(classification_report(ytest, y_pred))
print("ROC-AUC:", roc_auc_score(ytest, y_proba))
print(confusion_matrix(ytest, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.68      0.69     43586
           1       0.68      0.70      0.69     43079

    accuracy                           0.69     86665
   macro avg       0.69      0.69      0.69     86665
weighted avg       0.69      0.69      0.69     86665

ROC-AUC: 0.7444997574707153
[[29578 14008]
 [12734 30345]]

In [54]:
model = RandomForestClassifier( random_state=42, max_depth=7)
model.fit(xtrain, ytrain)

RandomForestClassifier(max_depth=7, random_state=42)

In [55]:
y_pred = model.predict(xtest)
y_proba = model.predict_proba(xtest)[:, 1]

print(classification_report(ytest, y_pred))
print("ROC-AUC:", roc_auc_score(ytest, y_proba))
print(confusion_matrix(ytest, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.99      0.94     43586
           1       0.99      0.89      0.94     43079

    accuracy                           0.94     86665
   macro avg       0.95      0.94      0.94     86665
weighted avg       0.95      0.94      0.94     86665

ROC-AUC: 0.9774224370568194
[[43199   387]
 [ 4749 38330]]

In [56]:
xtrain.columns = xtrain.columns.astype(str)
xtrain.columns = (
    xtrain.columns
    .str.replace('[', '(', regex=False)
    .str.replace(']', ')', regex=False)
    .str.replace('<', 'less_than', regex=False)
)
xtest.columns = (
    xtest.columns
    .str.replace('[', '(', regex=False)
    .str.replace(']', ')', regex=False)
    .str.replace('<', 'less_than', regex=False)
)

In [57]:
model = xgb.XGBClassifier(n_estimators=100, max_depth=7)
model.fit(xtrain, ytrain)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [58]:
y_pred = model.predict(xtest)
y_proba = model.predict_proba(xtest)[:, 1]

print(classification_report(ytest, y_pred))
print("ROC-AUC:", roc_auc_score(ytest, y_proba))
print(confusion_matrix(ytest, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96     43586
           1       0.99      0.93      0.96     43079

    accuracy                           0.96     86665
   macro avg       0.96      0.96      0.96     86665
weighted avg       0.96      0.96      0.96     86665

ROC-AUC: 0.9826703840589905
[[43053   533]
 [ 3149 39930]]

 **While the model demonstrates strong baseline performance, minimizing False Negatives is a critical clinical priority. Misclassifying a high-mortality risk patient as low-risk carries life-threatening consequences, whereas the reverse scenario (overestimating risk) is an acceptable trade-off. Consequently, our optimization strategy will strictly prioritize maximizing Recall (Sensitivity) to a target range of 0.99 to 1.00**

In [63]:

y_proba = model.predict_proba(xtest)[:, 1]
y_pred = y_proba>0.3
print(classification_report(ytest, y_pred))
print("ROC-AUC:", roc_auc_score(ytest, y_proba))
print(confusion_matrix(ytest, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95     43586
           1       0.96      0.94      0.95     43079

    accuracy                           0.95     86665
   macro avg       0.95      0.95      0.95     86665
weighted avg       0.95      0.95      0.95     86665

ROC-AUC: 0.9826703840589905
[[42044  1542]
 [ 2567 40512]]

**Hyperparameter Tuning could not be done due to system constraints**

In [65]:
# --- Saving the model ---
# 'wb' means Writing in Binary mode
with open('xgb_mortality_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model successfully saved as a pickle file.")

Model successfully saved as a pickle file.